export type City = {
  city: string;
  country: string;
  district: string;
  internationalPct: number;
  domesticPct: number;
  nightlifeDensity: number; // establishments / km², rough district estimate
  densityVsAmsterdamPct: number;
  densityMethod: string;
  walkability: number; // 1-10 beach-to-bar transition
  registeredPopulation: number;
  populationYear: number;
  monthlyLocalCostUsd: number; // normal solo local-ish living midpoint, not luxury expat
  monthlyCostRangeUsd: [number, number];
  beachDistanceKm: number;
  confidence: 'low' | 'medium' | 'high';
  verdict: 'top pick' | 'possible' | 'weak fit' | 'reject';
  tags: string[];
  notes: string;
  sourceUrls: string[];
};

export const AMSTERDAM_REFERENCE_DENSITY = 700;

const pct = (density: number) => Math.round((density / AMSTERDAM_REFERENCE_DENSITY) * 100);

export const cities: City[] = [
  {
    city: 'Bang Saen',
    country: 'Thailand',
    district: 'Bang Saen Beach / Walking Street / Saen Suk beachfront',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Weekend walking-street + beachfront food/bar cluster over ~0.8km²; OSM/travel-list proxy, medium confidence.',
    walkability: 8,
    registeredPopulation: 46658,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 850],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['domestic-heavy', 'student/local', 'weekend-crowded', 'cheap-eats'],
    notes: 'Probably the most local/domestic answer: Thai weekend beach town, student energy, food-heavy promenade. Beach quality is not tropical-postcard.',
    sourceUrls: [
      'http://citypopulation.de/en/thailand/eastern/chonburi/2094__saen_suk/',
      'https://wikitravel.org/wiki/en/index.php?title=Bang_Saen&mobileaction=toggle_view_desktop',
      'https://www.saensukcity.go.th/en/history.html',
      'https://www.tripadvisor.com/Attraction_Review-g2706695-d9997469-Reviews-Bangsaen_Walking_Street-Bangsaen_Chonburi_Province.html',
      'https://www.thestreetfoodguy.com/bang-saen-beach-street-food/',
    ],
  },
  {
    city: 'Hua Hin',
    country: 'Thailand',
    district: 'Soi Bintabaht / Night Market / central beach grid',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 520,
    densityVsAmsterdamPct: pct(520),
    densityMethod: 'Central bar/night-market grid within ~0.7km²; many venues but less packed than Amsterdam.',
    walkability: 8,
    registeredPopulation: 65983,
    populationYear: 2019,
    monthlyLocalCostUsd: 1050,
    monthlyCostRangeUsd: [850, 1500],
    beachDistanceKm: 0.25,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['domestic-weekends', 'expat', 'comfortable', 'bangkok-access'],
    notes: 'Best polished Thai option: Thai weekenders + expats, compact enough in the core, but more mature/resort than young-local party.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/western/prachuap_khiri_khan/7798__hua_hin',
      'https://internationalliving.com/countries/thailand/hua-hin-thailand/',
      'https://huahintoday.com/hua-hin-news/hua-hin-sees-tourism-boost-during-long-weekend-with-hotel-occupancy-at-80/',
      'https://www.numbeo.com/cost-of-living/in/Hua-Hin-Thailand',
    ],
  },
  {
    city: 'Vung Tau',
    country: 'Vietnam',
    district: 'Back Beach / Front Beach / central peninsula',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 390,
    densityVsAmsterdamPct: pct(390),
    densityMethod: 'Seafood/cafe/bar corridors around Back/Front Beach; linear urban strip, not fine-grain European grid.',
    walkability: 7,
    registeredPopulation: 341552,
    populationYear: 2019,
    monthlyLocalCostUsd: 675,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.2,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['domestic-heavy', 'hcmc-weekenders', 'urban-beach', 'affordable'],
    notes: 'Strong domestic Vietnamese beach city; weekends are very local/HCMC-driven. Nightlife moderate, not as dense as Nha Trang.',
    sourceUrls: [
      'https://www.citypopulation.de/en/vietnam/cities/',
      'https://internationalliving.com/countries/vietnam/vung-tau-vietnam/',
      'https://en.wikivoyage.org/wiki/Vung_Tau',
      'https://www.vietnam-briefing.com/news/vietnams-tourism-boom-during-tet-2025-leading-destinations-and-insights.html/',
    ],
  },
  {
    city: 'Malacca',
    country: 'Malaysia',
    district: 'Jonker Street / Bandar Hilir heritage core',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 800,
    densityVsAmsterdamPct: pct(800),
    densityMethod: 'Dense shophouse heritage grid; restaurant/cafe/bar density can exceed Amsterdam, but beach is weak.',
    walkability: 7,
    registeredPopulation: 579000,
    populationYear: 2020,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 0.9,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['heritage-grid', 'domestic-weekends', 'food', 'not-true-beach'],
    notes: 'Closest to European urban density. Caveat: coastal/river heritage city, not a proper beach-nightlife town.',
    sourceUrls: [
      'https://whc.unesco.org/en/list/1223/',
      'https://www.expatexchange.com/gdc/5/75/5302/Malaysia/Malacca',
      'https://mytourismdata.tourism.gov.my/',
      'https://en.wikipedia.org/wiki/Malacca_City',
    ],
  },
  {
    city: 'Nha Trang',
    country: 'Vietnam',
    district: 'Tran Phu beachfront / central tourist quarter',
    internationalPct: 50,
    domesticPct: 50,
    nightlifeDensity: 620,
    densityVsAmsterdamPct: pct(620),
    densityMethod: 'Dense beach promenade + tourist-quarter venue cluster; 20+ bars/clubs cited plus many restaurants/cafes.',
    walkability: 8.5,
    registeredPopulation: 422601,
    populationYear: 2019,
    monthlyLocalCostUsd: 820,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'possible',
    tags: ['dense-nightlife', 'international', 'urban-beach', 'resort-city'],
    notes: 'Best pure beach+bar density in Vietnam, but too internationally exposed if the domestic filter is strict.',
    sourceUrls: [
      'https://www.citypopulation.de/en/vietnam/admin/kh%C3%A1nh_h%C3%B2a/568__nha_trang/',
      'https://internationalliving.com/countries/vietnam/nha-trang-vietnam/',
      'https://vinwonders.com/en/wonderpedia/news/cost-of-living-in-nha-trang-vietnam/',
      'https://en.wikivoyage.org/wiki/Nha_Trang',
    ],
  },
  {
    city: 'Da Nang',
    country: 'Vietnam',
    district: 'An Thuong / My An / My Khe beach',
    internationalPct: 60,
    domesticPct: 40,
    nightlifeDensity: 560,
    densityVsAmsterdamPct: pct(560),
    densityMethod: 'Compact expat/digital-nomad beach neighborhood with cafes, bars, restaurants over ~1km².',
    walkability: 8,
    registeredPopulation: 988561,
    populationYear: 2019,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.35,
    confidence: 'high',
    verdict: 'possible',
    tags: ['best-livability', 'international', 'nomad', 'airport'],
    notes: 'Excellent long-stay infrastructure and walkability, but An Thuong is exactly the kind of international enclave the original filter disliked.',
    sourceUrls: [
      'https://www.citypopulation.de/en/vietnam/cities/',
      'https://internationalliving.com/countries/vietnam/da-nang-vietnam/',
      'https://ahoyvietnam.com/living-in-da-nang/',
      'https://en.wikivoyage.org/wiki/Da_Nang',
    ],
  },
  {
    city: 'George Town',
    country: 'Malaysia',
    district: 'Chulia Street / Love Lane / heritage core',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 760,
    densityVsAmsterdamPct: pct(760),
    densityMethod: 'UNESCO shophouse grid: high cafe/bar/restaurant density; real beach zone is outside core.',
    walkability: 8,
    registeredPopulation: 794313,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1400],
    beachDistanceKm: 2.0,
    confidence: 'high',
    verdict: 'possible',
    tags: ['heritage-grid', 'food', 'nomad', 'beach-not-adjacent'],
    notes: 'A great city grid, not a beach grid. Batu Ferringhi/Tanjung Bungah provide beach access but dilute walkability.',
    sourceUrls: [
      'https://whc.unesco.org/en/list/1223/',
      'https://www.goatsontheroad.com/living-in-penang/',
      'https://mypenang.gov.my/',
      'https://open.dosm.gov.my/',
    ],
  },
  {
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    district: 'KK Waterfront / Gaya Street / Tanjung Aru',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Waterfront/Gaya clusters plus Tanjung Aru food stalls; split nodes reduce true compact density.',
    walkability: 6,
    registeredPopulation: 500421,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1200],
    beachDistanceKm: 0.4,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['nature-gateway', 'airport', 'sunset-beach', 'split-node'],
    notes: 'Good real city + beach/airport hybrid. Less compact nightlife; more nature/adventure gateway than bar grid.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Kota_Kinabalu',
      'https://www.tripadvisor.com/Attraction_Review-g298307-d9696088-Reviews-Tanjung_Aru_Beach-Kota_Kinabalu_Kota_Kinabalu_District_West_Coast_Division_Sabah.html',
      'https://www.sabahtourism.com/statistics/',
      'https://travel.state.gov/en/international-travel/travel-advisories/malaysia.html',
    ],
  },
  {
    city: 'Langkawi',
    country: 'Malaysia',
    district: 'Pantai Cenang / Pantai Tengah; Kuah for services',
    internationalPct: 40,
    domesticPct: 60,
    nightlifeDensity: 380,
    densityVsAmsterdamPct: pct(380),
    densityMethod: 'Beach strip bars/restaurants in Cenang/Tengah; Kuah excluded from nightlife density.',
    walkability: 7,
    registeredPopulation: 94777,
    populationYear: 2020,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [650, 1200],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['island', 'duty-free', 'beach-strip', 'car-dependent'],
    notes: 'Best Malaysia island option. Cenang is walkable/social; wider island requires scooter/car.',
    sourceUrls: [
      'https://internationalliving.com/countries/malaysia/langkawi-malaysia/',
      'https://www.willflyforfood.net/the-first-timers-travel-guide-to-langkawi-malaysia/',
      'https://naturallylangkawi.my/',
      'https://en.wikipedia.org/wiki/Langkawi',
    ],
  },
  {
    city: 'Phu Quoc',
    country: 'Vietnam',
    district: 'Duong Dong / Long Beach / Night Market',
    internationalPct: 40,
    domesticPct: 60,
    nightlifeDensity: 360,
    densityVsAmsterdamPct: pct(360),
    densityMethod: 'Night market + Long Beach bars; island sprawl lowers effective density.',
    walkability: 6.5,
    registeredPopulation: 179480,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1200],
    beachDistanceKm: 0.35,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['island', 'night-market', 'domestic-rising', 'sprawl'],
    notes: 'Good island vibe and night market; less dense and more transport-dependent than Da Nang/Nha Trang.',
    sourceUrls: [
      'https://internationalliving.com/countries/vietnam/phu-quoc-vietnam/',
      'https://www.citypopulation.de/en/vietnam/kiengiang/admin/ph%C3%BA_qu%E1%BB%91c/31078__d%C6%B0%C6%A1ng_%C4%91%C3%B4ng/',
      'https://www.expatexchange.com/gdc/2/119/8112/Vietnam/Ph%C3%BA-Quoc-Island',
      'https://en.wikivoyage.org/wiki/Phu_Quoc',
    ],
  },
  {
    city: 'Cha-am',
    country: 'Thailand',
    district: 'Cha-am beachfront road',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 190,
    densityVsAmsterdamPct: pct(190),
    densityMethod: 'Long family beach strip with restaurants; few true bars/clubs.',
    walkability: 7,
    registeredPopulation: 20000,
    populationYear: 2024,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [600, 1150],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['domestic-family', 'quiet', 'cheap', 'low-nightlife'],
    notes: 'Very domestic and affordable, but too sleepy for Rembrandtplein-style density.',
    sourceUrls: [
      'https://www.tourismthailand.org/Destinations/Provinces/Cha-am/241',
      'https://chaam.org/cha-am/cost-of-living',
      'https://tiptop-travel.com/thailand-travel-guides/central-thailand/phetchaburi/cha-am/',
      'https://www.saporedicina.com/english/traveling-to-cha-am/',
    ],
  },
  {
    city: 'Prachuap Khiri Khan',
    country: 'Thailand',
    district: 'Ao Prachuap waterfront / town center',
    internationalPct: 10,
    domesticPct: 90,
    nightlifeDensity: 130,
    densityVsAmsterdamPct: pct(130),
    densityMethod: 'Compact local waterfront restaurants/cafes; very few bars.',
    walkability: 8,
    registeredPopulation: 18568,
    populationYear: 2019,
    monthlyLocalCostUsd: 620,
    monthlyCostRangeUsd: [500, 850],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['very-local', 'quiet', 'cheap', 'scenic'],
    notes: 'Excellent cheap authentic coastal town. Fails nightlife density, not walkability.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/western/prachuap_khiri_khan/7799__prachuap_khiri_khan/',
      'https://www.numbeo.com/cost-of-living/in/Prachuap-Khiri-Khan-Thailand',
      'https://en.wikivoyage.org/wiki/Prachuap_Khiri_Khan',
    ],
  },
  {
    city: 'Port Dickson',
    country: 'Malaysia',
    district: 'Teluk Kemang / PD waterfront resort strip',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 180,
    densityVsAmsterdamPct: pct(180),
    densityMethod: 'Domestic beach/resort strip; restaurants/hotels spread along coast, limited bar density.',
    walkability: 5,
    registeredPopulation: 119300,
    populationYear: 2020,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [550, 950],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['domestic-weekends', 'kl-access', 'quiet', 'spread-out'],
    notes: 'Very domestic and near KL, but more sleepy resort strip than urban nightlife grid.',
    sourceUrls: [
      'https://www.earthvagabonds.com/port-dickson-is-quiet-and-peaceful-for-budget-slow-travelers/',
      'https://caffeinatedexcursions.com/should-you-visit-port-dickson-malaysia-an-honest-review/',
      'https://www.malaysia.travel/explore/port-dickson',
      'https://open.dosm.gov.my/',
    ],
  },
  {
    city: 'Kampot',
    country: 'Cambodia',
    district: 'Old Market / riverside town center',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 260,
    densityVsAmsterdamPct: pct(260),
    densityMethod: 'Riverside cafe/bar grid over small core; not beach-adjacent.',
    walkability: 4,
    registeredPopulation: 50000,
    populationYear: 2019,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [600, 900],
    beachDistanceKm: 5,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['riverside', 'expat', 'cheap', 'not-beach'],
    notes: 'Best Cambodia lifestyle town, but it is riverside. Good cafés, weak beach transition.',
    sourceUrls: [
      'https://madmonkeyhostels.com/blogs/kampot-digital-nomad-guide/',
      'https://internationalliving.com/countries/cambodia/kampot-cambodia/',
      'https://en.wikivoyage.org/wiki/Kampot',
      'https://nis.gov.kh',
    ],
  },
  {
    city: 'Kuta Lombok',
    country: 'Indonesia',
    district: 'Kuta village / Mandalika beachfront',
    internationalPct: 55,
    domesticPct: 45,
    nightlifeDensity: 320,
    densityVsAmsterdamPct: pct(320),
    densityMethod: 'Growing surf-town restaurant/bar strip; compact village but still low-rise/spread.',
    walkability: 6.5,
    registeredPopulation: 10000,
    populationYear: 2024,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1200],
    beachDistanceKm: 0.25,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['surf', 'international', 'fast-development', 'airport-close'],
    notes: 'Best Bali alternative in Indonesia, but the main social scene is international/surf-facing.',
    sourceUrls: [
      'https://thehoneycombers.com/bali/kuta-lombok-guide-indonesia/',
      'https://rinjanidawnadventures.com/mandalika-lombok/',
      'https://www.bbc.com/news/articles/c5yp87ppk7eo',
      'https://lomboktengahkab.bps.go.id',
    ],
  },
  {
    city: 'Panglao',
    country: 'Philippines',
    district: 'Alona Beach / Danao / Panglao tourism core',
    internationalPct: 50,
    domesticPct: 50,
    nightlifeDensity: 300,
    densityVsAmsterdamPct: pct(300),
    densityMethod: 'Alona beachfront and back-road bar/restaurant cluster; resort strip rather than urban grid.',
    walkability: 7,
    registeredPopulation: 39339,
    populationYear: 2020,
    monthlyLocalCostUsd: 1000,
    monthlyCostRangeUsd: [800, 1500],
    beachDistanceKm: 0.05,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['beach-resort', 'airport', 'diving', 'touristy'],
    notes: 'Good beach+airport access. Too resort/international and not dense enough for the original target.',
    sourceUrls: [
      'https://3d-universal.com/en/blogs/where-to-stay-in-bohol-for-digital-nomad.html',
      'https://www.abrahamtours.com/philippines/digital-nomad-guide-philippines/',
      'https://psa.gov.ph/statistics/population-and-housing',
      'https://tourism.bohol.gov.ph/',
    ],
  },
  {
    city: 'Siargao',
    country: 'Philippines',
    district: 'General Luna / Tourism Road / Cloud 9 corridor',
    internationalPct: 55,
    domesticPct: 45,
    nightlifeDensity: 240,
    densityVsAmsterdamPct: pct(240),
    densityMethod: 'Tourism Road restaurants/bars spread over several km; strong scene but low density.',
    walkability: 6,
    registeredPopulation: 22108,
    populationYear: 2020,
    monthlyLocalCostUsd: 1100,
    monthlyCostRangeUsd: [850, 1600],
    beachDistanceKm: 0.3,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['surf', 'nomad', 'island', 'brownout-risk'],
    notes: 'Strong social island, but more international surf/nomad corridor than domestic city grid.',
    sourceUrls: [
      'https://www.coworksurf.com/blog/the-ultimate-digital-nomad-guide-to-siargao',
      'https://nomads.com/cost-of-living/in/siargao',
      'https://psa.gov.ph/statistics/population-and-housing',
      'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Philippines.html',
    ],
  },
  {
    city: 'Dumaguete',
    country: 'Philippines',
    district: 'Rizal Boulevard / Baywalk',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 310,
    densityVsAmsterdamPct: pct(310),
    densityMethod: 'Waterfront/social strip + downtown food/bar cluster; not a swimmable beach strip.',
    walkability: 7,
    registeredPopulation: 134103,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 1.5,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['budget', 'expat', 'waterfront', 'not-beach'],
    notes: 'Very good cheap coastal lifestyle city. But Baywalk is waterfront, not beach nightlife.',
    sourceUrls: [
      'https://nomadranker.com/cities/dumaguete/',
      'https://www.expatexchange.com/gdc/2/90/6101/Philippines/Dumaguete',
      'https://dumaguetecity.gov.ph/',
      'https://psa.gov.ph/statistics/population-and-housing',
    ],
  },
  {
    city: 'Subic / Olongapo',
    country: 'Philippines',
    district: 'Subic Freeport / Barretto / Baloy Beach',
    internationalPct: 30,
    domesticPct: 70,
    nightlifeDensity: 280,
    densityVsAmsterdamPct: pct(280),
    densityMethod: 'Barretto/Baloy bars and freeport restaurants are split nodes; moderate density.',
    walkability: 5.5,
    registeredPopulation: 260317,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.3,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['domestic-drive-market', 'expat', 'bay', 'split-node'],
    notes: 'Practical domestic/expat bay base near Manila/Clark. Not a compact urban beach-bar grid.',
    sourceUrls: [
      'https://www.expatexchange.com/gdc/2/90/9858/Philippines/Subic-Bay',
      'https://www.mysubicbay.com.ph/',
      'https://psa.gov.ph/statistics/population-and-housing',
    ],
  },
  {
    city: 'Koh Lanta',
    country: 'Thailand',
    district: 'Long Beach / Klong Dao / Saladan clusters',
    internationalPct: 55,
    domesticPct: 45,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Beach bars/restaurants spread along long west-coast strip; high season dependent.',
    walkability: 5,
    registeredPopulation: 26805,
    populationYear: 2010,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1400],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['island', 'seasonal', 'international', 'scooter-needed'],
    notes: 'Lovely laid-back island, but low density and seasonal. Scooter needed for most life.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/admin/krabi/8103__ko_lanta/',
      'https://www.expatexchange.com/gdc/2/108/5992/Thailand/Koh-Lanta',
      'https://en.wikivoyage.org/wiki/Ko_Lanta',
    ],
  },
  {
    city: 'Belitung / Tanjung Pandan',
    country: 'Indonesia',
    district: 'Tanjung Pandan / beach-resort access to Tanjung Tinggi',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 170,
    densityVsAmsterdamPct: pct(170),
    densityMethod: 'Town restaurants and resort/beach venues are dispersed; holiday island, not nightlife grid.',
    walkability: 4,
    registeredPopulation: 190000,
    populationYear: 2023,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [550, 950],
    beachDistanceKm: 0.7,
    confidence: 'low',
    verdict: 'weak fit',
    tags: ['domestic-island', 'quiet', 'beautiful-beaches', 'low-nightlife'],
    notes: 'Strong domestic island/beach escape from Jakarta. Weak for dense nightlife/long-stay scene.',
    sourceUrls: [
      'https://www.jakartaexpats.com/belitung.html',
      'https://belitungkab.bps.go.id',
      'https://belitonggeopark.net',
    ],
  },
  {
    city: 'Kep',
    country: 'Cambodia',
    district: 'Crab Market / Kep Beach waterfront',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 120,
    densityVsAmsterdamPct: pct(120),
    densityMethod: 'Small crab-market restaurant cluster; almost no bar grid.',
    walkability: 3,
    registeredPopulation: 42000,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 850],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['quiet', 'seafood', 'small-town', 'no-nightlife'],
    notes: 'Nice quiet coast and seafood; fails the bar-density requirement hard.',
    sourceUrls: [
      'https://www.expatexchange.com/gdc/2/211/10330/Cambodia/Kep',
      'https://en.wikivoyage.org/wiki/Kep',
      'https://nis.gov.kh',
    ],
  },
  {
    city: 'Sihanoukville',
    country: 'Cambodia',
    district: 'Serendipity / Ochheuteal / casino-beach zones',
    internationalPct: 65,
    domesticPct: 35,
    nightlifeDensity: 300,
    densityVsAmsterdamPct: pct(300),
    densityMethod: 'Bars/casinos/restaurants exist, but urban fabric is chaotic and not pleasant walkable grid.',
    walkability: 3,
    registeredPopulation: 100000,
    populationYear: 2019,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [650, 1100],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['casino', 'international', 'reputation-risk', 'island-gateway'],
    notes: 'Has infrastructure and beaches, but too casino/international/chaotic for the target.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Sihanoukville',
      'https://ips-cambodia.com/fr/whats-next-for-sihanoukville-cambodias-coastal-growth/',
      'https://internationalliving.com/countries/cambodia/sihanoukville-cambodia/',
      'https://nis.gov.kh',
    ],
  },
  {
    city: 'Makassar',
    country: 'Indonesia',
    district: 'Losari waterfront / city center',
    internationalPct: 10,
    domesticPct: 90,
    nightlifeDensity: 330,
    densityVsAmsterdamPct: pct(330),
    densityMethod: 'Large city food/cafe/waterfront density; Losari is promenade, not beach.',
    walkability: 4,
    registeredPopulation: 1423000,
    populationYear: 2023,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [550, 950],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['big-city', 'domestic', 'waterfront', 'not-beach'],
    notes: 'Big domestic city and waterfront, but not beach-nightlife. Better as eastern Indonesia hub.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Makassar',
      'https://makassarkota.bps.go.id',
      'https://makassarkota.go.id',
    ],
  },
  {
    city: 'Manado',
    country: 'Indonesia',
    district: 'Boulevard / waterfront city center',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 260,
    densityVsAmsterdamPct: pct(260),
    densityMethod: 'City restaurants/cafes plus dive tourism; beach/island access separated from city nightlife.',
    walkability: 4,
    registeredPopulation: 460000,
    populationYear: 2023,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [600, 1000],
    beachDistanceKm: 1.5,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['diving', 'domestic', 'gateway', 'not-beach-grid'],
    notes: 'Good dive/nature city. Does not solve walkable beach bar-density brief.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Manado',
      'https://www.expat.or.id/info/manado.html',
      'https://manadokota.bps.go.id',
    ],
  },
  {
    city: 'Balikpapan',
    country: 'Indonesia',
    district: 'Kemala / Melawai / city waterfront',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 250,
    densityVsAmsterdamPct: pct(250),
    densityMethod: 'Corporate city restaurants/cafes; beaches secondary and nodes spread out.',
    walkability: 4,
    registeredPopulation: 735000,
    populationYear: 2023,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [700, 1200],
    beachDistanceKm: 0.5,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['corporate-expat', 'domestic', 'clean-city', 'not-nightlife'],
    notes: 'Safe/clean corporate expat city, not a beach-bar density candidate.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Balikpapan',
      'https://www.expat.or.id/info/balikpapan.html',
      'https://balikpapankota.bps.go.id',
    ],
  },
  {
    city: 'Padang',
    country: 'Indonesia',
    district: 'Padang Beach / city waterfront',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Food/waterfront activity, but limited bar scene due to local cultural context.',
    walkability: 5,
    registeredPopulation: 930000,
    populationYear: 2023,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['domestic', 'food', 'mentawai-gateway', 'low-bar-scene'],
    notes: 'Great food/culture and domestic coastal city; not bar-heavy.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Padang',
      'https://padangkota.bps.go.id',
      'https://sumbar.bps.go.id',
    ],
  },
  {
    city: 'Desaru',
    country: 'Malaysia',
    district: 'Desaru Coast resort strip',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 120,
    densityVsAmsterdamPct: pct(120),
    densityMethod: 'Purpose-built resort coast; low organic restaurant/bar grid.',
    walkability: 3,
    registeredPopulation: 20000,
    populationYear: 2020,
    monthlyLocalCostUsd: 1000,
    monthlyCostRangeUsd: [800, 1400],
    beachDistanceKm: 0.1,
    confidence: 'low',
    verdict: 'reject',
    tags: ['resort', 'singapore-weekend', 'low-grid', 'family'],
    notes: 'Good resort weekend, weak long-stay/nightlife grid.',
    sourceUrls: [
      'https://trulyexpattravel.com/desaru-coast-guide/',
      'https://mondosol.com/desaru-travel-guide/',
      'https://www.desarucoast.com/',
    ],
  },
  {
    city: 'Karimunjawa',
    country: 'Indonesia',
    district: 'Main village / harbor / beach access',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 80,
    densityVsAmsterdamPct: pct(80),
    densityMethod: 'Small island village; warungs/guesthouses, almost no bar grid.',
    walkability: 3,
    registeredPopulation: 11000,
    populationYear: 2023,
    monthlyLocalCostUsd: 600,
    monthlyCostRangeUsd: [450, 850],
    beachDistanceKm: 0.4,
    confidence: 'low',
    verdict: 'reject',
    tags: ['remote-island', 'domestic', 'snorkeling', 'no-nightlife'],
    notes: 'Beautiful island retreat. Not a city, not reliable dense nightlife.',
    sourceUrls: [
      'https://www.adventuresofjellie.com/indonesia/complete-karimunjawa-guide',
      'https://www.workaway.info/en/host/387464641229',
      'https://jeparakab.bps.go.id',
      'https://tnkarimunjawa.id',
    ],
  },
  {
    city: 'Parangtritis',
    country: 'Indonesia',
    district: 'Parangtritis Beach / Yogyakarta south coast',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 90,
    densityVsAmsterdamPct: pct(90),
    densityMethod: 'Domestic day-trip beach stalls; no real bar/nightlife grid.',
    walkability: 2,
    registeredPopulation: 10000,
    populationYear: 2023,
    monthlyLocalCostUsd: 500,
    monthlyCostRangeUsd: [400, 700],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['domestic-daytrip', 'dangerous-swim', 'no-nightlife'],
    notes: 'Very domestic, but rip-current/high-wave risk and no nightlife. Day trip only.',
    sourceUrls: [
      'https://www.ipb.ac.id/news/index/2025/02/rip-current-danger-ipb-university-lecturer-reminds-tourists-to-be-vigilant/',
      'https://en.tempo.co/read/2015829/tourists-warned-of-high-waves-on-yogyakarta-beaches',
      'https://pariwisata.bantulkab.go.id',
      'https://visitingjogja.jogjaprov.go.id',
    ],
  },
];
