export type City = {
  city: string;
  country: string;
  district: string;
  internationalPct: number;
  domesticPct: number;
  nightlifeDensity: number; // bars/clubs/restaurants per km² in the vacation nightlife core, rough estimate
  densityVsAmsterdamPct: number;
  densityMethod: string;
  nightlifeCompactness: number; // 1-10: are most bars/clubs in one walkable area?
  swimmability: number; // 1-10: beach quality + safe/easy swimming for a normal vacation day
  walkability: number; // 1-10: beach-to-nightlife transition
  registeredPopulation: number;
  populationYear: number;
  monthlyLocalCostUsd: number; // normal solo local-ish monthly baseline, secondary metric only
  monthlyCostRangeUsd: [number, number];
  beachDistanceKm: number;
  confidence: 'low' | 'medium' | 'high';
  verdict: 'top pick' | 'possible' | 'weak fit' | 'reject';
  tags: string[];
  notes: string;
  sourceUrls: string[];
};

export const AMSTERDAM_REFERENCE_DENSITY = 700;

const pct = (density: number) => Math.round((density / AMSTERDAM_REFERENCE_DENSITY) * 100);

export const cities: City[] = [
  {
    city: 'Hua Hin',
    country: 'Thailand',
    district: 'Soi Bintabaht / Night Market / central beach grid',
    internationalPct: 20,
    domesticPct: 80,
    nightlifeDensity: 520,
    densityVsAmsterdamPct: pct(520),
    densityMethod: 'Central bar/night-market grid within ~0.7km²; compact enough for bar hopping, less intense than Patong/Nha Trang.',
    nightlifeCompactness: 7,
    swimmability: 7,
    walkability: 8,
    registeredPopulation: 65983,
    populationYear: 2019,
    monthlyLocalCostUsd: 1050,
    monthlyCostRangeUsd: [850, 1500],
    beachDistanceKm: 0.25,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['best-balance', 'swimmable', 'domestic-weekends', 'compact-core'],
    notes: 'Best balanced fit: real swimmable beach, walkable nightlife core, still mostly Thai/domestic compared with island hubs.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/western/prachuap_khiri_khan/7798__hua_hin',
      'https://internationalliving.com/countries/thailand/hua-hin-thailand/',
      'https://huahintoday.com/hua-hin-news/hua-hin-sees-tourism-boost-during-long-weekend-with-hotel-occupancy-at-80/',
      'https://www.numbeo.com/cost-of-living/in/Hua-Hin-Thailand',
    ],
  },
  {
    city: 'Vung Tau',
    country: 'Vietnam',
    district: 'Back Beach / Front Beach / central peninsula',
    internationalPct: 3,
    domesticPct: 97,
    nightlifeDensity: 390,
    densityVsAmsterdamPct: pct(390),
    densityMethod: 'Back/Front Beach food, cafe, beer, and bar corridors; more weekend-local than club-heavy.',
    nightlifeCompactness: 6,
    swimmability: 6,
    walkability: 7,
    registeredPopulation: 341552,
    populationYear: 2019,
    monthlyLocalCostUsd: 675,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.2,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['lowest-international', 'domestic-weekends', 'swimmable-enough', 'hcmc-access'],
    notes: 'Strong low-foreigner pick. Beach is usable but not pristine; nightlife is busy on weekends rather than Amsterdam/Patong dense.',
    sourceUrls: [
      'https://www.citypopulation.de/en/vietnam/cities/',
      'https://internationalliving.com/countries/vietnam/vung-tau-vietnam/',
      'https://en.wikivoyage.org/wiki/Vung_Tau',
      'https://www.vietnam-briefing.com/news/vietnams-tourism-boom-during-tet-2025-leading-destinations-and-insights.html/',
    ],
  },
  {
    city: 'Bang Saen',
    country: 'Thailand',
    district: 'Bang Saen Beach / Wonnapha / Walking Street',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Beach-road food/bar/student/weekend cluster over ~0.8km²; compact and local, but not a polished resort strip.',
    nightlifeCompactness: 7,
    swimmability: 5.5,
    walkability: 8,
    registeredPopulation: 46658,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 850],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['very-local', 'student-energy', 'weekend-crowded', 'beach-quality-caveat'],
    notes: 'Best local/domestic Thai social beach town. It qualifies because the beach is swimmable, but beach quality is the main compromise.',
    sourceUrls: [
      'http://citypopulation.de/en/thailand/eastern/chonburi/2094__saen_suk/',
      'https://wikitravel.org/wiki/en/index.php?title=Bang_Saen&mobileaction=toggle_view_desktop',
      'https://www.saensukcity.go.th/en/history.html',
      'https://www.tripadvisor.com/Attraction_Review-g2706695-d9997469-Reviews-Bangsaen_Walking_Street-Bangsaen_Chonburi_Province.html',
    ],
  },
  {
    city: 'Langkawi',
    country: 'Malaysia',
    district: 'Pantai Cenang beach road',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 380,
    densityVsAmsterdamPct: pct(380),
    densityMethod: 'Pantai Cenang beach-road bars/restaurants in a single walkable strip; not club-dense but coherent.',
    nightlifeCompactness: 7,
    swimmability: 8,
    walkability: 8,
    registeredPopulation: 64000,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [750, 1300],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['swimmable', 'compact-strip', 'domestic-majority', 'island'],
    notes: 'Best Malaysia fit: proper swimmable beach plus one obvious bar/restaurant strip, while still majority domestic/regional.',
    sourceUrls: [
      'https://www.citypopulation.de/en/malaysia/kedah/admin/0207__langkawi/',
      'https://www.langkawi.com/pantai-cenang/',
      'https://www.numbeo.com/cost-of-living/in/Langkawi',
      'https://mytourismdata.tourism.gov.my/',
    ],
  },
  {
    city: 'Nha Trang',
    country: 'Vietnam',
    district: 'Tran Phu / Biet Thu beach nightlife core',
    internationalPct: 30,
    domesticPct: 70,
    nightlifeDensity: 620,
    densityVsAmsterdamPct: pct(620),
    densityMethod: 'Dense beach promenade + tourist-quarter bar/club cluster; one of Vietnam’s strongest beach-nightlife cores.',
    nightlifeCompactness: 8,
    swimmability: 8,
    walkability: 8.5,
    registeredPopulation: 422601,
    populationYear: 2019,
    monthlyLocalCostUsd: 820,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['best-nightlife-density', 'swimmable', 'urban-beach', 'higher-international'],
    notes: 'Probably the best pure beach + compact nightlife product in Vietnam. International share is the penalty, not the beach/nightlife fit.',
    sourceUrls: [
      'https://www.citypopulation.de/en/vietnam/admin/kh%C3%A1nh_h%C3%B2a/568__nha_trang/',
      'https://internationalliving.com/countries/vietnam/nha-trang-vietnam/',
      'https://vinwonders.com/en/wonderpedia/news/cost-of-living-in-nha-trang-vietnam/',
      'https://en.wikivoyage.org/wiki/Nha_Trang',
    ],
  },
  {
    city: 'Da Nang',
    country: 'Vietnam',
    district: 'An Thuong / My An / My Khe beach',
    internationalPct: 38,
    domesticPct: 62,
    nightlifeDensity: 560,
    densityVsAmsterdamPct: pct(560),
    densityMethod: 'An Thuong is a compact beach-adjacent restaurant/bar grid; density strong, but internationally visible.',
    nightlifeCompactness: 7,
    swimmability: 8,
    walkability: 8,
    registeredPopulation: 988561,
    populationYear: 2019,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.35,
    confidence: 'high',
    verdict: 'possible',
    tags: ['excellent-beach', 'compact-grid', 'nomad-heavy', 'higher-international'],
    notes: 'Excellent vacation practicality and beach walkability. Penalized because the exact nightlife area is fairly international/nomad-heavy.',
    sourceUrls: [
      'https://www.citypopulation.de/en/vietnam/cities/',
      'https://internationalliving.com/countries/vietnam/da-nang-vietnam/',
      'https://ahoyvietnam.com/living-in-da-nang/',
      'https://en.wikivoyage.org/wiki/Da_Nang',
    ],
  },
  {
    city: 'Siargao',
    country: 'Philippines',
    district: 'General Luna / Tourism Road',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 340,
    densityVsAmsterdamPct: pct(340),
    densityMethod: 'Tourism Road bars/restaurants are compact and social; official island mix is more domestic, General Luna feels more foreign-visible.',
    nightlifeCompactness: 8,
    swimmability: 6,
    walkability: 7,
    registeredPopulation: 35799,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [750, 1350],
    beachDistanceKm: 0.3,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['compact-social-core', 'surf', 'domestic-majority', 'swimming-caveat'],
    notes: 'Great compact social/nightlife strip and still majority domestic overall. Beach swimming is uneven because surf/reef/tides matter.',
    sourceUrls: [
      'https://www.citypopulation.de/en/philippines/mindanao/admin/surigao_del_norte/166722__general_luna/',
      'https://guidetothephilippines.ph/articles/what-to-experience/siargao-tourist-spots',
      'https://www.numbeo.com/cost-of-living/in/Siargao',
    ],
  },
  {
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    district: 'Waterfront / Gaya Street / Tanjung Aru',
    internationalPct: 30,
    domesticPct: 70,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Waterfront/Gaya nightlife and Tanjung Aru beach are separate nodes; good city-break fit, weaker beach-bar adjacency.',
    nightlifeCompactness: 6,
    swimmability: 6,
    walkability: 6,
    registeredPopulation: 500421,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1200],
    beachDistanceKm: 0.4,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['city-break', 'sunset-beach', 'domestic-majority', 'split-nodes'],
    notes: 'Worth keeping, but not a clean beach-nightlife strip: the beach and nightlife clusters are close enough by taxi, not one continuous grid.',
    sourceUrls: [
      'https://www.citypopulation.de/en/malaysia/sabah/admin/1201__kota_kinabalu/',
      'https://en.wikivoyage.org/wiki/Kota_Kinabalu',
      'https://www.sabahtourism.com/',
      'https://www.numbeo.com/cost-of-living/in/Kota-Kinabalu',
    ],
  },
  {
    city: 'Phu Quoc',
    country: 'Vietnam',
    district: 'Duong Dong / Long Beach / night market',
    internationalPct: 17,
    domesticPct: 83,
    nightlifeDensity: 260,
    densityVsAmsterdamPct: pct(260),
    densityMethod: 'Excellent beaches, but nightlife is split between night market, resorts, beach bars, and Sunset Town rather than one dense bar grid.',
    nightlifeCompactness: 4,
    swimmability: 9,
    walkability: 5,
    registeredPopulation: 146028,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['excellent-beach', 'domestic-majority', 'spread-out-nightlife', 'island'],
    notes: 'Great vacation island and low-ish international share, but fails the dense nightlife requirement compared with Nha Trang/Da Nang/Langkawi.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Phu_Quoc',
      'https://vietnamtourism.gov.vn/en/post/19768',
      'https://www.numbeo.com/cost-of-living/in/Phu-Quoc',
    ],
  },
  {
    city: 'Panglao',
    country: 'Philippines',
    district: 'Alona Beach strip',
    internationalPct: 50,
    domesticPct: 50,
    nightlifeDensity: 300,
    densityVsAmsterdamPct: pct(300),
    densityMethod: 'Alona Beach is a real compact beach nightlife strip; visitor mix in the core is much more international than Bohol overall.',
    nightlifeCompactness: 8,
    swimmability: 8,
    walkability: 8,
    registeredPopulation: 39578,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.05,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['classic-beach-nightlife', 'swimmable', 'compact-strip', 'too-international'],
    notes: 'Very good beach/nightlife fit. It only falls because Alona is visibly international-tourist heavy.',
    sourceUrls: [
      'https://www.citypopulation.de/en/philippines/visayas/admin/bohol/071233__panglao/',
      'https://guidetothephilippines.ph/articles/what-to-experience/alona-beach-bohol-guide',
      'https://www.numbeo.com/cost-of-living/in/Bohol',
    ],
  },
  {
    city: 'Kuta Lombok',
    country: 'Indonesia',
    district: 'Kuta town / Mandalika / beach road',
    internationalPct: 55,
    domesticPct: 45,
    nightlifeDensity: 320,
    densityVsAmsterdamPct: pct(320),
    densityMethod: 'Kuta village has a compact restaurant/bar strip; best swimming beaches are nearby rather than always directly in town.',
    nightlifeCompactness: 7,
    swimmability: 7,
    walkability: 6,
    registeredPopulation: 104000,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.25,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['beautiful-beaches', 'compact-core', 'surfer-backpacker', 'too-international'],
    notes: 'Good vacation product, but Kuta’s core is internationally oriented; include as a benchmark, not a low-foreigner winner.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Kuta_(Lombok)',
      'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/lombok',
      'https://www.numbeo.com/cost-of-living/in/Lombok',
    ],
  },
  {
    city: 'Phuket',
    country: 'Thailand',
    district: 'Patong / Bangla Road / Patong Beach',
    internationalPct: 80,
    domesticPct: 20,
    nightlifeDensity: 760,
    densityVsAmsterdamPct: pct(760),
    densityMethod: 'Bangla Road + Patong Beach tourist strip; benchmark for dense beach nightlife, but internationally dominated.',
    nightlifeCompactness: 10,
    swimmability: 8,
    walkability: 9,
    registeredPopulation: 79000,
    populationYear: 2019,
    monthlyLocalCostUsd: 1300,
    monthlyCostRangeUsd: [950, 1800],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['benchmark', 'dense-nightlife', 'swimmable', 'too-international'],
    notes: 'Keep as the negative control: it has the exact beach/nightlife density, but fails the low-international requirement hard.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/southern/phuket/8301__phuket/',
      'https://en.wikivoyage.org/wiki/Phuket',
      'https://en.wikivoyage.org/wiki/Patong',
      'https://www.numbeo.com/cost-of-living/in/Phuket',
    ],
  },
  {
    city: 'Koh Samui',
    country: 'Thailand',
    district: 'Chaweng Beach / Soi Green Mango',
    internationalPct: 65,
    domesticPct: 35,
    nightlifeDensity: 650,
    densityVsAmsterdamPct: pct(650),
    densityMethod: 'Chaweng has a compact beach-road nightlife zone with clubs/bars; very strong product, very international.',
    nightlifeCompactness: 9,
    swimmability: 8,
    walkability: 9,
    registeredPopulation: 67600,
    populationYear: 2019,
    monthlyLocalCostUsd: 1250,
    monthlyCostRangeUsd: [900, 1700],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['great-beach-nightlife', 'too-international', 'benchmark'],
    notes: 'Strong beach-nightlife vacation option, but it behaves more like a foreign-tourist island hub than the target.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Ko_Samui',
      'https://en.wikivoyage.org/wiki/Chaweng',
      'https://www.numbeo.com/cost-of-living/in/Ko-Samui',
    ],
  },
  {
    city: 'Pattaya',
    country: 'Thailand',
    district: 'Walking Street / LK Metro / Pattaya Beach',
    internationalPct: 50,
    domesticPct: 50,
    nightlifeDensity: 820,
    densityVsAmsterdamPct: pct(820),
    densityMethod: 'Very dense nightlife corridor, but beach quality and international/sexpat skew are serious negatives.',
    nightlifeCompactness: 9,
    swimmability: 4.5,
    walkability: 8,
    registeredPopulation: 119532,
    populationYear: 2019,
    monthlyLocalCostUsd: 1100,
    monthlyCostRangeUsd: [800, 1600],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['dense-nightlife', 'weak-beach', 'too-international', 'benchmark'],
    notes: 'Useful benchmark for nightlife density, but it is not the beach-vacation winner because swimming/beach feel is weak.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/eastern/chonburi/2099__pattaya/',
      'https://en.wikivoyage.org/wiki/Pattaya',
      'https://www.numbeo.com/cost-of-living/in/Pattaya',
    ],
  },
  {
    city: 'Cha-am',
    country: 'Thailand',
    district: 'Cha-am beachfront / night market',
    internationalPct: 2,
    domesticPct: 98,
    nightlifeDensity: 190,
    densityVsAmsterdamPct: pct(190),
    densityMethod: 'Domestic beach strip with seafood, markets, and some bars; nightlife is thin rather than bustling.',
    nightlifeCompactness: 4.5,
    swimmability: 6,
    walkability: 7,
    registeredPopulation: 27923,
    populationYear: 2019,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [550, 950],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['very-local', 'swimmable', 'quiet', 'low-nightlife-density'],
    notes: 'Local and beachy, but too quiet for the “bustling dense nightlife” goal.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/western/phetchaburi/7697__cha_am/',
      'https://en.wikivoyage.org/wiki/Cha-am',
      'https://www.numbeo.com/cost-of-living/in/Cha-Am',
    ],
  },
  {
    city: 'Subic / Olongapo',
    country: 'Philippines',
    district: 'Barretto / Baloy Beach / Magsaysay Drive',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 280,
    densityVsAmsterdamPct: pct(280),
    densityMethod: 'Barretto/Baloy has a compact nightlife strip; beach/bay quality is mediocre and expat-bar skew is visible.',
    nightlifeCompactness: 7,
    swimmability: 5,
    walkability: 6,
    registeredPopulation: 260317,
    populationYear: 2020,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 0.3,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['compact-bars', 'domestic-majority', 'mediocre-beach', 'expat-skew'],
    notes: 'Nightlife compactness exists, but the beach-vacation quality is not strong enough.',
    sourceUrls: [
      'https://www.citypopulation.de/en/philippines/luzon/admin/zambales/037107__olongapo/',
      'https://en.wikivoyage.org/wiki/Olongapo',
      'https://en.wikivoyage.org/wiki/Subic',
    ],
  },
  {
    city: 'Belitung / Tanjung Pandan',
    country: 'Indonesia',
    district: 'Tanjung Pendam / Tanjung Kelayang',
    internationalPct: 3,
    domesticPct: 97,
    nightlifeDensity: 120,
    densityVsAmsterdamPct: pct(120),
    densityMethod: 'Very low-foreigner beach destination, but restaurants/cafes are quiet and nightlife is not concentrated.',
    nightlifeCompactness: 3,
    swimmability: 8,
    walkability: 4,
    registeredPopulation: 103000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.7,
    confidence: 'low',
    verdict: 'weak fit',
    tags: ['excellent-beach', 'very-local', 'quiet-nightlife'],
    notes: 'Good counterexample: low international + good beach, but nightlife is too quiet for this project.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Belitung',
      'https://www.indonesia.travel/gb/en/destinations/sumatra/belitung',
      'https://www.numbeo.com/cost-of-living/in/Tanjung-Pandan',
    ],
  },
  {
    city: 'Port Dickson',
    country: 'Malaysia',
    district: 'Teluk Kemang / PD waterfront',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 140,
    densityVsAmsterdamPct: pct(140),
    densityMethod: 'Mostly family/domestic beach hotels, seafood, and scattered venues; no dense bar/club core.',
    nightlifeCompactness: 2,
    swimmability: 5,
    walkability: 4,
    registeredPopulation: 119300,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['very-local', 'weak-nightlife', 'family-beach'],
    notes: 'Low international share is attractive, but nightlife is not dense/bustling enough.',
    sourceUrls: [
      'https://www.citypopulation.de/en/malaysia/negerisembilan/admin/0504__port_dickson/',
      'https://en.wikivoyage.org/wiki/Port_Dickson',
      'https://mytourismdata.tourism.gov.my/',
    ],
  },
  {
    city: 'Desaru',
    country: 'Malaysia',
    district: 'Desaru Coast resort strip',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 80,
    densityVsAmsterdamPct: pct(80),
    densityMethod: 'Resort-contained beach area; no walkable public bar/club grid.',
    nightlifeCompactness: 2,
    swimmability: 6,
    walkability: 3,
    registeredPopulation: 47100,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.1,
    confidence: 'low',
    verdict: 'reject',
    tags: ['resort-beach', 'weak-nightlife', 'not-walkable-grid'],
    notes: 'Beach/resort weekend spot, not a dense nightlife vacation town.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Desaru',
      'https://www.desarucoast.com/',
      'https://mytourismdata.tourism.gov.my/',
    ],
  },
  {
    city: 'George Town',
    country: 'Malaysia',
    district: 'Chulia/Love Lane core; Batu Ferringhi beach separate',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 760,
    densityVsAmsterdamPct: pct(760),
    densityMethod: 'Great shophouse food/bar grid in George Town, but the swimmable beach zone is far away and much less nightlife-dense.',
    nightlifeCompactness: 4,
    swimmability: 5,
    walkability: 2,
    registeredPopulation: 794313,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1400],
    beachDistanceKm: 9,
    confidence: 'high',
    verdict: 'reject',
    tags: ['great-city-bars', 'beach-split', 'not-beach-nightlife'],
    notes: 'Was overrated before. Great urban density, but not a swimmable-beach nightlife spot.',
    sourceUrls: [
      'https://whc.unesco.org/en/list/1223/',
      'https://www.goatsontheroad.com/living-in-penang/',
      'https://mypenang.gov.my/',
      'https://open.dosm.gov.my/',
    ],
  },
  {
    city: 'Malacca',
    country: 'Malaysia',
    district: 'Jonker Street / Bandar Hilir heritage core',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 800,
    densityVsAmsterdamPct: pct(800),
    densityMethod: 'Dense heritage food/bar grid, but it is a river/coastal city rather than a swimmable beach vacation spot.',
    nightlifeCompactness: 8,
    swimmability: 1,
    walkability: 2,
    registeredPopulation: 579000,
    populationYear: 2020,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 8,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['city-grid', 'not-swimmable-beach', 'old-objective-false-positive'],
    notes: 'Explicit audit correction: great dense city core, wrong objective. Not a beach vacation nightlife spot.',
    sourceUrls: [
      'https://whc.unesco.org/en/list/1223/',
      'https://www.expatexchange.com/gdc/5/75/5302/Malaysia/Malacca',
      'https://mytourismdata.tourism.gov.my/',
      'https://en.wikipedia.org/wiki/Malacca_City',
    ],
  },
  {
    city: 'Kampot',
    country: 'Cambodia',
    district: 'Riverside old town',
    internationalPct: 8,
    domesticPct: 92,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Pleasant riverside bar/cafe town; not a beach destination.',
    nightlifeCompactness: 4,
    swimmability: 1,
    walkability: 2,
    registeredPopulation: 49700,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 25,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['riverside', 'not-beach', 'quiet'],
    notes: 'Low international share, but wrong category: it is riverside, not swimmable-beach nightlife.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Kampot',
      'https://www.numbeo.com/cost-of-living/in/Kampot',
    ],
  },
  {
    city: 'Kep',
    country: 'Cambodia',
    district: 'Kep Beach / crab market',
    internationalPct: 10,
    domesticPct: 90,
    nightlifeDensity: 90,
    densityVsAmsterdamPct: pct(90),
    densityMethod: 'Small beach and crab market; very limited nightlife.',
    nightlifeCompactness: 2,
    swimmability: 4,
    walkability: 4,
    registeredPopulation: 41000,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.2,
    confidence: 'low',
    verdict: 'reject',
    tags: ['quiet', 'weak-nightlife', 'small-beach'],
    notes: 'Too quiet and beach is only modest; not a bustling nightlife target.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Kep',
      'https://www.numbeo.com/cost-of-living/in/Kep',
    ],
  },
  {
    city: 'Sihanoukville',
    country: 'Cambodia',
    district: 'Serendipity / Otres / casino coast',
    internationalPct: 9,
    domesticPct: 91,
    nightlifeDensity: 240,
    densityVsAmsterdamPct: pct(240),
    densityMethod: 'Some nightlife remains, but city beach reputation, casino/construction pattern, and pollution concerns make it a poor vacation fit.',
    nightlifeCompactness: 5,
    swimmability: 4.5,
    walkability: 5,
    registeredPopulation: 89000,
    populationYear: 2019,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.2,
    confidence: 'low',
    verdict: 'reject',
    tags: ['beach-quality-risk', 'casino-skew', 'reject'],
    notes: 'Low-ish international percentage is misleading; beach quality/reputation and nightlife shape are wrong.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Sihanoukville',
      'https://www.numbeo.com/cost-of-living/in/Sihanoukville',
    ],
  },
  {
    city: 'Dumaguete',
    country: 'Philippines',
    district: 'Rizal Boulevard / Dauin access',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Town nightlife exists, but city has no proper swimmable beach strip; Dauin/Apo are excursions.',
    nightlifeCompactness: 4,
    swimmability: 3,
    walkability: 2,
    registeredPopulation: 134103,
    populationYear: 2020,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [550, 1000],
    beachDistanceKm: 12,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['expat-town', 'not-beach-strip', 'weak-fit'],
    notes: 'Useful town, wrong product: no dense nightlife directly on a swimmable vacation beach.',
    sourceUrls: [
      'https://www.citypopulation.de/en/philippines/visayas/admin/negros_oriental/074612__dumaguete/',
      'https://en.wikivoyage.org/wiki/Dumaguete',
    ],
  },
  {
    city: 'Jakarta',
    country: 'Indonesia',
    district: 'SCBD / Senopati / Kemang; Ancol coast proxy',
    internationalPct: 20,
    domesticPct: 80,
    nightlifeDensity: 780,
    densityVsAmsterdamPct: pct(780),
    densityMethod: 'Excellent dense city nightlife, but not connected to a real swimmable vacation beach.',
    nightlifeCompactness: 9,
    swimmability: 1,
    walkability: 1,
    registeredPopulation: 10679000,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1400],
    beachDistanceKm: 12,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['baseline', 'city-nightlife', 'not-beach-vacation'],
    notes: 'Baseline/control: dense and local, but should not score because swimmable beach vacation fit is basically absent.',
    sourceUrls: [
      'https://www.citypopulation.de/en/indonesia/admin/31__jakarta_raya/',
      'https://en.wikivoyage.org/wiki/Jakarta',
      'https://en.wikivoyage.org/wiki/Jakarta/South',
      'https://www.numbeo.com/cost-of-living/in/Jakarta',
    ],
  },
  {
    city: 'Surabaya',
    country: 'Indonesia',
    district: 'Tunjungan / Gubeng / Pakuwon; Kenjeran coast proxy',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 520,
    densityVsAmsterdamPct: pct(520),
    densityMethod: 'Local urban nightlife/food districts; coast is separate and not a swimmable vacation beach zone.',
    nightlifeCompactness: 6,
    swimmability: 1,
    walkability: 1,
    registeredPopulation: 2875000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 950],
    beachDistanceKm: 8,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['baseline', 'local-city', 'not-beach-vacation'],
    notes: 'Another false-positive control: very local and cheap, but not a beach vacation nightlife destination.',
    sourceUrls: [
      'https://www.citypopulation.de/en/indonesia/admin/3578__surabaya/',
      'https://en.wikivoyage.org/wiki/Surabaya',
      'https://www.numbeo.com/cost-of-living/in/Surabaya',
    ],
  },
  {
    city: 'Bangkok',
    country: 'Thailand',
    district: 'Sukhumvit / Thonglor / RCA / Khao San',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 900,
    densityVsAmsterdamPct: pct(900),
    densityMethod: 'Excellent dense nightlife baseline; no beach.',
    nightlifeCompactness: 10,
    swimmability: 0,
    walkability: 0,
    registeredPopulation: 5527000,
    populationYear: 2020,
    monthlyLocalCostUsd: 1150,
    monthlyCostRangeUsd: [850, 1700],
    beachDistanceKm: 145,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['baseline', 'mega-city', 'not-beach'],
    notes: 'Keep only as a nightlife-density benchmark. It should be rejected by the beach/swimmability logic.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/admin/10__bangkok/',
      'https://en.wikivoyage.org/wiki/Bangkok/Sukhumvit',
      'https://en.wikivoyage.org/wiki/Bangkok/Khao_San_Road',
      'https://www.numbeo.com/cost-of-living/in/Bangkok',
    ],
  },
];
