export type Confidence = 'high' | 'medium' | 'low';

export interface City {
  city: string;
  country: string;
  district: string;
  internationalPct: number;
  domesticPct: number;
  nightlifeDensity: number;
  densityVsAmsterdamPct: number;
  densityMethod: string;
  nightlifeCompactness: number;
  swimmability: number;
  beachQualityScore: number;
  waterCleanlinessScore: number;
  currentSafetyScore: number;
  eveningBeachLifeScore: number;
  barClusterRadiusMeters: number;
  barsWithin10MinWalk: number;
  lateNightVenuesCount: number;
  beachAudit: string;
  nightlifeAudit: string;
  walkability: number;
  registeredPopulation: number;
  populationYear: number;
  monthlyLocalCostUsd: number;
  monthlyCostRangeUsd: [number, number];
  beachDistanceKm: number;
  confidence: Confidence;
  verdict: 'top pick' | 'possible' | 'weak fit' | 'reject';
  tags: string[];
  notes: string;
  sourceUrls: string[];
}

export const AMSTERDAM_REFERENCE_DENSITY = 700;

const pct = (density: number) => Math.round((density / AMSTERDAM_REFERENCE_DENSITY) * 100);

export const cities: City[] = [
  {
    city: 'Hua Hin',
    country: 'Thailand',
    district: 'Soi Bintabaht / Night Market / central beach grid',
    internationalPct: 12,
    domesticPct: 88,
    nightlifeDensity: 520,
    densityVsAmsterdamPct: pct(520),
    densityMethod: 'Central bar/night-market grid within ~0.7km²; compact enough for bar hopping, less intense than Patong/Nha Trang.',
    nightlifeCompactness: 7,
    swimmability: 5.5,
    beachQualityScore: 6.0,
    waterCleanlinessScore: 4.5,
    currentSafetyScore: 6.5,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 500,
    barsWithin10MinWalk: 35,
    lateNightVenuesCount: 12,
    beachAudit: 'Long sandy beach suitable for wading, but Reddit/traveler consensus notes shallow, murky Gulf water and seasonal box jellyfish warnings (Jun-Oct).',
    nightlifeAudit: 'Soi Bintabaht + night-market grid is walkable and bar-hop friendly, though less intense than Patong/Pattaya.',
    walkability: 8,
    registeredPopulation: 65983,
    populationYear: 2019,
    monthlyLocalCostUsd: 1050,
    monthlyCostRangeUsd: [850, 1500],
    beachDistanceKm: 0.25,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['best-balance', 'domestic-weekends', 'compact-core', 'shallow-water'],
    notes: 'Online consensus: Excellent domestic Bangkok weekend atmosphere; ocean water is safe but cloudy/murky rather than clear blue.',
    sourceUrls: [
      'https://www.tourismthailand.org/Destinations/Provinces/Prachuap%20Khiri%20Khan/231',
      'https://www.mots.go.th/news/category/758',
      'https://www.citypopulation.de/en/thailand/western/prachuap_khiri_khan/7798__hua_hin',
      'https://internationalliving.com/countries/thailand/hua-hin-thailand/',
      'https://www.numbeo.com/cost-of-living/in/Hua-Hin-Thailand',
    ],
  },
  {
    city: 'Vung Tau',
    country: 'Vietnam',
    district: 'Back Beach / Front Beach / central peninsula',
    internationalPct: 3,
    domesticPct: 97,
    nightlifeDensity: 390,
    densityVsAmsterdamPct: pct(390),
    densityMethod: 'Back/Front Beach food, cafe, beer, and bar corridors; more weekend-local than club-heavy.',
    nightlifeCompactness: 6,
    swimmability: 4.5,
    beachQualityScore: 5.5,
    waterCleanlinessScore: 3.5,
    currentSafetyScore: 3.5,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 12,
    lateNightVenuesCount: 6,
    beachAudit: 'Popular HCMC weekend getaway, but Back Beach has strong rip currents and seasonal trash/hyacinth washing ashore from the Mekong delta.',
    nightlifeAudit: 'Moderate Back/Front Beach bar scene; better as domestic weekend energy than true club density.',
    walkability: 7,
    registeredPopulation: 341552,
    populationYear: 2019,
    monthlyLocalCostUsd: 675,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['lowest-international', 'domestic-weekends', 'hcmc-access', 'rip-current-warning'],
    notes: 'Online sentiment: Extremely local Vietnamese weekend destination (<3% foreign); water is swimmable but rip currents require caution.',
    sourceUrls: [
      'https://vir.com.vn/ba-ria-vung-tau-eyes-tourism-advances-122038-122038.html',
      'https://www.citypopulation.de/en/vietnam/cities/',
      'https://internationalliving.com/countries/vietnam/vung-tau-vietnam/',
      'https://en.wikivoyage.org/wiki/Vung_Tau',
    ],
  },
  {
    city: 'Bang Saen',
    country: 'Thailand',
    district: 'Bang Saen Beach / Wonnapha / Walking Street',
    internationalPct: 8,
    domesticPct: 92,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Beach-road food/bar/student/weekend cluster over ~0.8km²; compact and local, but not a polished resort strip.',
    nightlifeCompactness: 7,
    swimmability: 3.5,
    beachQualityScore: 4.5,
    waterCleanlinessScore: 2.5,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 20,
    lateNightVenuesCount: 6,
    beachAudit: 'Very authentic Thai university/weekend beach, but Gulf estuary location causes murky green water and winter algae/plankton blooms.',
    nightlifeAudit: 'Local/student beach-road bars and cafes; compact enough, not a deep late-night district.',
    walkability: 8,
    registeredPopulation: 46658,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 850],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['very-local', 'student-energy', 'weekend-crowded', 'murky-water-caveat'],
    notes: 'Online sentiment: Pure Thai domestic crowd and great beach promenade food, but ocean water clarity is low.',
    sourceUrls: [
      'https://www.tourismthailand.org/Attraction/bang-saen-beach',
      'https://www.mots.go.th/news/category/758',
      'http://citypopulation.de/en/thailand/eastern/chonburi/2094__saen_suk/',
    ],
  },
  {
    city: 'Langkawi',
    country: 'Malaysia',
    district: 'Pantai Cenang beach road',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 380,
    densityVsAmsterdamPct: pct(380),
    densityMethod: 'Pantai Cenang beach-road bars/restaurants in a single walkable strip; duty-free alcohol prices.',
    nightlifeCompactness: 7,
    swimmability: 7.5,
    beachQualityScore: 7.5,
    waterCleanlinessScore: 6.5,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 800,
    barsWithin10MinWalk: 10,
    lateNightVenuesCount: 4,
    beachAudit: 'Pantai Cenang is a long swimmable resort beach with warm waters; water is pleasant, though slightly murky near shore.',
    nightlifeAudit: 'Compact beach-road/night-beach cluster with duty-free alcohol, relaxed reggae/acoustic beach bars.',
    walkability: 8,
    registeredPopulation: 64000,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [750, 1300],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'top pick',
    tags: ['swimmable', 'compact-strip', 'domestic-majority', 'island', 'duty-free'],
    notes: 'Online sentiment: Domestic-heavy Malaysian island with duty-free drinks and good swimmable beach strip.',
    sourceUrls: [
      'https://www.lada.gov.my/en/statistics/',
      'https://www.citypopulation.de/en/malaysia/kedah/admin/0207__langkawi/',
      'https://www.numbeo.com/cost-of-living/in/Langkawi',
    ],
  },
  {
    city: 'Nha Trang',
    country: 'Vietnam',
    district: 'Tran Phu / Biet Thu beach nightlife core',
    internationalPct: 43,
    domesticPct: 57,
    nightlifeDensity: 620,
    densityVsAmsterdamPct: pct(620),
    densityMethod: 'Dense beach promenade + tourist-quarter bar/club cluster; one of Vietnam’s strongest beach-nightlife cores.',
    nightlifeCompactness: 8,
    swimmability: 7.5,
    beachQualityScore: 7.0,
    waterCleanlinessScore: 6.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 700,
    barsWithin10MinWalk: 20,
    lateNightVenuesCount: 10,
    beachAudit: 'Convenient urban swim beach along Tran Phu boulevard; winter monsoon waves (Oct-Jan) bring rough seas and urban runoff.',
    nightlifeAudit: 'Tran Phu/Biet Thu has vibrant beach clubs (Sailing Club) and late-night venues.',
    walkability: 8.5,
    registeredPopulation: 422601,
    populationYear: 2019,
    monthlyLocalCostUsd: 820,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['best-nightlife-density', 'swimmable', 'urban-beach', 'higher-international'],
    notes: 'Online sentiment: Excellent urban beach nightlife, though winter monsoon brings rougher water and international tourist count is high.',
    sourceUrls: [
      'https://vietnamtourism.gov.vn/en/post/20745',
      'https://internationalliving.com/countries/vietnam/nha-trang-vietnam/',
      'https://en.wikivoyage.org/wiki/Nha_Trang',
    ],
  },
  {
    city: 'Da Nang',
    country: 'Vietnam',
    district: 'An Thuong / My An / My Khe beach',
    internationalPct: 38,
    domesticPct: 62,
    nightlifeDensity: 560,
    densityVsAmsterdamPct: pct(560),
    densityMethod: 'An Thuong is a compact beach-adjacent restaurant/bar grid; density strong, but internationally visible.',
    nightlifeCompactness: 7,
    swimmability: 7.5,
    beachQualityScore: 8.0,
    waterCleanlinessScore: 7.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 800,
    barsWithin10MinWalk: 25,
    lateNightVenuesCount: 12,
    beachAudit: 'My Khe is a wide clean sandy beach; morning swimming is calm and clear, while winter monsoon afternoons bring surf and rip currents.',
    nightlifeAudit: 'An Thuong/My An gives a proper beach-adjacent restaurant/bar grid popular with digital nomads.',
    walkability: 8,
    registeredPopulation: 988561,
    populationYear: 2019,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.35,
    confidence: 'high',
    verdict: 'possible',
    tags: ['excellent-beach', 'compact-grid', 'nomad-heavy', 'higher-international'],
    notes: 'Online sentiment: Clean wide beach and lively An Thuong nomad bar grid, though foreign presence is prominent.',
    sourceUrls: [
      'https://en.baodanang.vn/da-nang-welcomes-12-8-million-visitors-in-8-months-of-2025-3300752.html',
      'https://ahoyvietnam.com/living-in-da-nang/',
    ],
  },
  {
    city: 'Siargao',
    country: 'Philippines',
    district: 'General Luna / Tourism Road',
    internationalPct: 10,
    domesticPct: 90,
    nightlifeDensity: 340,
    densityVsAmsterdamPct: pct(340),
    densityMethod: 'Tourism Road bars/restaurants are compact and social; General Luna hosts rotating nightly party venues.',
    nightlifeCompactness: 8,
    swimmability: 5.5,
    beachQualityScore: 8.0,
    waterCleanlinessScore: 7.5,
    currentSafetyScore: 4.5,
    eveningBeachLifeScore: 9.0,
    barClusterRadiusMeters: 1500,
    barsWithin10MinWalk: 10,
    lateNightVenuesCount: 6,
    beachAudit: 'Famous surf island (Cloud 9); town beaches have shallow sharp reef flats and heavy surf, making casual ocean swimming tricky.',
    nightlifeAudit: 'General Luna has a world-famous rotating party schedule (Flotsam & Jetsam, Harana, loose beach bars).',
    walkability: 7,
    registeredPopulation: 35799,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [750, 1350],
    beachDistanceKm: 0.3,
    confidence: 'high',
    verdict: 'possible',
    tags: ['compact-social-core', 'surf', 'domestic-majority', 'surf-reef-caveat'],
    notes: 'Online sentiment: Incredible island surf vibe and rotating nightlife; reef flats require care for non-surfer swimming.',
    sourceUrls: [
      'https://www.foi.gov.ph/agencies/dot/siargao-tourism-statistics/',
      'https://www.rappler.com/philippines/mindanao/siargao-tourism-rides-high-surge-february-2024/',
    ],
  },
  {
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    district: 'Waterfront / Gaya Street / Tanjung Aru',
    internationalPct: 33,
    domesticPct: 67,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Waterfront/Gaya nightlife and Tanjung Aru beach are separate nodes; good city-break fit.',
    nightlifeCompactness: 6,
    swimmability: 5.5,
    beachQualityScore: 6.0,
    waterCleanlinessScore: 5.5,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 1200,
    barsWithin10MinWalk: 8,
    lateNightVenuesCount: 5,
    beachAudit: 'Tanjung Aru is a world-class sunset spot, but ocean water is murky; island boat trips (Tunku Abdul Rahman park) are needed for clear swimming.',
    nightlifeAudit: 'KK waterfront bars are lively, but separated from the sunset beach by distance.',
    walkability: 6,
    registeredPopulation: 500421,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1200],
    beachDistanceKm: 0.4,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['city-break', 'sunset-beach', 'domestic-majority', 'split-nodes'],
    notes: 'Online sentiment: Great sunsets and seafood; island boat trips needed for crystal clear swimming.',
    sourceUrls: [
      'https://sabahtourism.com/statistics/',
      'https://www.numbeo.com/cost-of-living/in/Kota-Kinabalu',
    ],
  },
  {
    city: 'Phu Quoc',
    country: 'Vietnam',
    district: 'Duong Dong / Long Beach / night market',
    internationalPct: 16,
    domesticPct: 84,
    nightlifeDensity: 260,
    densityVsAmsterdamPct: pct(260),
    densityMethod: 'Nightlife is split between night market, resorts, Long Beach bars, and Grand World/Sunset Town.',
    nightlifeCompactness: 4,
    swimmability: 8.0,
    beachQualityScore: 8.0,
    waterCleanlinessScore: 6.0,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 7.0,
    barClusterRadiusMeters: 1200,
    barsWithin10MinWalk: 16,
    lateNightVenuesCount: 8,
    beachAudit: 'Long Beach has calm swimmable water in dry season (Nov-Apr); plastic waste reports affect western beaches during monsoon (May-Oct); Sao & Starfish beaches cleaner.',
    nightlifeAudit: 'Beach bars and night market venues exist but are spread along Long Beach.',
    walkability: 5,
    registeredPopulation: 146028,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['excellent-beach', 'domestic-majority', 'spread-out-nightlife', 'island'],
    notes: 'Online sentiment: Excellent dry-season swimming on Sao/Long beach; plastic waste can affect western shores in monsoon.',
    sourceUrls: [
      'https://vietnamnews.vn/travel/1688354/kien-giang-welcomes-9-8-million-tourists-in-2024.html',
    ],
  },
  {
    city: 'Panglao',
    country: 'Philippines',
    district: 'Alona Beach strip',
    internationalPct: 36,
    domesticPct: 64,
    nightlifeDensity: 300,
    densityVsAmsterdamPct: pct(300),
    densityMethod: 'Alona Beach is a compact beachfront nightlife strip; visitor mix in the core skews international.',
    nightlifeCompactness: 8,
    swimmability: 7.0,
    beachQualityScore: 8.0,
    waterCleanlinessScore: 6.0,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 700,
    barsWithin10MinWalk: 12,
    lateNightVenuesCount: 5,
    beachAudit: 'Alona is a white-sand swim beach, though shallow sea urchin beds and dive boat anchoring require care.',
    nightlifeAudit: 'Beachfront resto-bar strip is coherent, with lively evening acoustic and bar vibe.',
    walkability: 8,
    registeredPopulation: 39578,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.05,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['classic-beach-nightlife', 'swimmable', 'compact-strip', 'too-international'],
    notes: 'Online sentiment: Beautiful white sand and lively beach bars; sea urchins and boat traffic near shore.',
    sourceUrls: [
      'https://ppdo.bohol.gov.ph/profile/socio-economic-profile/economic-development/tourism/visitor-arrivals/',
    ],
  },
  {
    city: 'Kuta Lombok',
    country: 'Indonesia',
    district: 'Kuta town / Mandalika / beach road',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 320,
    densityVsAmsterdamPct: pct(320),
    densityMethod: 'Kuta village has a compact restaurant/bar strip; best swimmable clear bays (Tanjung Aan, Mawun) are 10 mins away.',
    nightlifeCompactness: 7,
    swimmability: 7.5,
    beachQualityScore: 8.5,
    waterCleanlinessScore: 8.5,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 800,
    barsWithin10MinWalk: 25,
    lateNightVenuesCount: 8,
    beachAudit: 'Town beach is scenic; pristine turquoise swimming at nearby Tanjung Aan & Mawun bays.',
    nightlifeAudit: 'Small surf-town bar cluster with live music/DJs; social surf community vibe.',
    walkability: 6,
    registeredPopulation: 104000,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.25,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['beautiful-beaches', 'compact-core', 'surfer-backpacker', 'foreign-visible'],
    notes: 'Online sentiment: Outstanding turquoise bays nearby (Tanjung Aan); town has a great laid-back surf bar scene.',
    sourceUrls: [
      'https://lomboktengahkab.bps.go.id/',
    ],
  },
  {
    city: 'Phuket',
    country: 'Thailand',
    district: 'Patong / Bangla Road / Patong Beach',
    internationalPct: 75,
    domesticPct: 25,
    nightlifeDensity: 760,
    densityVsAmsterdamPct: pct(760),
    densityMethod: 'Bangla Road + Patong Beach tourist strip; benchmark for dense beach nightlife, but heavily foreign.',
    nightlifeCompactness: 10,
    swimmability: 7.0,
    beachQualityScore: 6.5,
    waterCleanlinessScore: 5.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 9.0,
    barClusterRadiusMeters: 700,
    barsWithin10MinWalk: 120,
    lateNightVenuesCount: 60,
    beachAudit: 'Patong is beach-adjacent and usable, but heavy jet-ski traffic and crowding degrade water quality; Kata/Karon cleaner.',
    nightlifeAudit: 'Bangla Road is the density benchmark and also the exact international-hub false positive.',
    walkability: 9,
    registeredPopulation: 79000,
    populationYear: 2019,
    monthlyLocalCostUsd: 1300,
    monthlyCostRangeUsd: [950, 1800],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['benchmark', 'dense-nightlife', 'swimmable', 'too-international'],
    notes: 'Audited benchmark: Patong offers extreme nightlife density and usable beach, but 75% foreign crowd fails local objective.',
    sourceUrls: [
      'https://www.tourismthailand.org/Attraction/patong-beach',
    ],
  },
  {
    city: 'Koh Samui',
    country: 'Thailand',
    district: 'Chaweng Beach / Soi Green Mango',
    internationalPct: 60,
    domesticPct: 40,
    nightlifeDensity: 650,
    densityVsAmsterdamPct: pct(650),
    densityMethod: 'Chaweng has a compact beach-road nightlife zone with clubs/bars; very strong product, very international.',
    nightlifeCompactness: 9,
    swimmability: 8.0,
    beachQualityScore: 8.0,
    waterCleanlinessScore: 7.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 9.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 80,
    lateNightVenuesCount: 35,
    beachAudit: 'Chaweng and Lamai are fine swimmable white sand beaches; water clarity is good during dry season (Jan-Apr).',
    nightlifeAudit: 'Chaweng is a strong island nightlife cluster with beach parties, clubs, and late venues.',
    walkability: 9,
    registeredPopulation: 67600,
    populationYear: 2019,
    monthlyLocalCostUsd: 1250,
    monthlyCostRangeUsd: [900, 1700],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['great-beach-nightlife', 'too-international', 'benchmark'],
    notes: 'Audited benchmark: High foreign tourism share; clean swimmable beach.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Ko_Samui',
    ],
  },
  {
    city: 'Pattaya',
    country: 'Thailand',
    district: 'Walking Street / LK Metro / Pattaya Beach',
    internationalPct: 50,
    domesticPct: 50,
    nightlifeDensity: 820,
    densityVsAmsterdamPct: pct(820),
    densityMethod: 'Very dense nightlife corridor, but beach quality and sexpat skew are serious negatives.',
    nightlifeCompactness: 9,
    swimmability: 3.5,
    beachQualityScore: 4.0,
    waterCleanlinessScore: 2.5,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 1000,
    barsWithin10MinWalk: 200,
    lateNightVenuesCount: 100,
    beachAudit: 'Pattaya Main Beach has heavy urban/boat pollution and poor water clarity; Jomtien Beach (3km south) is slightly better at 5/10.',
    nightlifeAudit: 'Walking Street/Beach Road is ultra-dense nightlife, making it a classic beach-quality false positive.',
    walkability: 8,
    registeredPopulation: 119532,
    populationYear: 2019,
    monthlyLocalCostUsd: 1100,
    monthlyCostRangeUsd: [800, 1600],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['dense-nightlife', 'weak-beach', 'too-international', 'benchmark'],
    notes: 'Audited: Ultra-dense nightlife, but main ocean beach water quality is poor.',
    sourceUrls: [
      'https://www.citypopulation.de/en/thailand/eastern/chonburi/2099__pattaya/',
    ],
  },
  {
    city: 'Cha-am',
    country: 'Thailand',
    district: 'Cha-am beachfront / night market',
    internationalPct: 8,
    domesticPct: 92,
    nightlifeDensity: 190,
    densityVsAmsterdamPct: pct(190),
    densityMethod: 'Domestic beach strip with seafood, markets, and some bars; nightlife is thin rather than bustling.',
    nightlifeCompactness: 4.5,
    swimmability: 5.5,
    beachQualityScore: 5.5,
    waterCleanlinessScore: 5.0,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 4.0,
    barClusterRadiusMeters: 700,
    barsWithin10MinWalk: 15,
    lateNightVenuesCount: 4,
    beachAudit: 'Long calm pine-lined family beach with fair water, shallow Gulf swimming, not a clear turquoise resort beach.',
    nightlifeAudit: 'Quiet local beach/night-market bars; too thin after dark for energetic nightlife.',
    walkability: 7,
    registeredPopulation: 27923,
    populationYear: 2019,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [550, 950],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['very-local', 'swimmable', 'quiet', 'low-nightlife-density'],
    notes: 'Audited: Bangkok domestic weekend market; peaceful shallow beach, low nightlife density.',
    sourceUrls: [
      'https://www.tourismthailand.org/Destinations/Provinces/Phetchaburi/228',
    ],
  },
  {
    city: 'Subic / Olongapo',
    country: 'Philippines',
    district: 'Barretto / Baloy Beach / Magsaysay Drive',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 280,
    densityVsAmsterdamPct: pct(280),
    densityMethod: 'Barretto/Baloy has a compact nightlife strip; beach/bay quality is mediocre and expat-bar skew is visible.',
    nightlifeCompactness: 7,
    swimmability: 3.5,
    beachQualityScore: 4.5,
    waterCleanlinessScore: 3.0,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 1000,
    barsWithin10MinWalk: 15,
    lateNightVenuesCount: 10,
    beachAudit: 'Barretto/Baloy features calm bay beaches, but naval shipping traffic and industrial runoff result in murky brown water.',
    nightlifeAudit: 'Dense expat/bar strip near the bay; nightlife stronger than beach quality.',
    walkability: 6,
    registeredPopulation: 260317,
    populationYear: 2020,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 0.3,
    confidence: 'low',
    verdict: 'weak fit',
    tags: ['compact-bars', 'domestic-majority', 'mediocre-beach', 'expat-skew'],
    notes: 'Audited: Industrial bay setting limits ocean swimmability; active expat bar scene.',
    sourceUrls: [
      'https://www.citypopulation.de/en/philippines/luzon/admin/zambales/037107__olongapo/',
    ],
  },
  {
    city: 'Belitung / Tanjung Pandan',
    country: 'Indonesia',
    district: 'Tanjung Pendam / Tanjung Kelayang',
    internationalPct: 2,
    domesticPct: 98,
    nightlifeDensity: 120,
    densityVsAmsterdamPct: pct(120),
    densityMethod: 'Very low-foreigner beach destination, but restaurants/cafes are quiet and nightlife is not concentrated.',
    nightlifeCompactness: 3,
    swimmability: 8.5,
    beachQualityScore: 9.0,
    waterCleanlinessScore: 9.0,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 5.0,
    barClusterRadiusMeters: 1000,
    barsWithin10MinWalk: 10,
    lateNightVenuesCount: 2,
    beachAudit: 'Pristine white beaches with massive granite boulders and crystal clear calm waters (Tanjung Tinggi / Kelayang).',
    nightlifeAudit: 'Mostly cafes, seafood, and occasional live music; very limited late-night depth.',
    walkability: 4,
    registeredPopulation: 103000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.7,
    confidence: 'high',
    verdict: 'weak fit',
    tags: ['excellent-beach', 'very-local', 'quiet-nightlife'],
    notes: 'Online sentiment: Pristine granite boulder beaches with crystal clear water; quiet evening scene.',
    sourceUrls: [
      'https://babel.bps.go.id/',
    ],
  },
  {
    city: 'Port Dickson',
    country: 'Malaysia',
    district: 'Teluk Kemang / PD waterfront',
    internationalPct: 5,
    domesticPct: 95,
    nightlifeDensity: 140,
    densityVsAmsterdamPct: pct(140),
    densityMethod: 'Mostly family/domestic beach hotels, seafood, and scattered venues; no dense bar/club core.',
    nightlifeCompactness: 2,
    swimmability: 3.5,
    beachQualityScore: 4.5,
    waterCleanlinessScore: 3.0,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 4.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 3,
    lateNightVenuesCount: 2,
    beachAudit: 'Popular domestic weekend beach, but Malacca Strait shipping lanes and oil refinery proximity cause murky water and litter.',
    nightlifeAudit: 'Nightlife is scattered hotel/resort bars rather than a compact district.',
    walkability: 4,
    registeredPopulation: 119300,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.1,
    confidence: 'low',
    verdict: 'reject',
    tags: ['very-local', 'weak-nightlife', 'family-beach'],
    notes: 'Klang Valley domestic weekend market; murky shipping strait water, weak bar scene.',
    sourceUrls: [
      'https://www.dosm.gov.my/',
    ],
  },
  {
    city: 'Desaru',
    country: 'Malaysia',
    district: 'Desaru Coast resort strip',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 80,
    densityVsAmsterdamPct: pct(80),
    densityMethod: 'Resort-contained beach area; no walkable public bar/club grid.',
    nightlifeCompactness: 2,
    swimmability: 6.5,
    beachQualityScore: 7.0,
    waterCleanlinessScore: 6.5,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 3.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 2,
    lateNightVenuesCount: 1,
    beachAudit: 'Long open ocean beach facing South China Sea; good sand and swimmable in calm season (Apr-Oct), monsoon waves in winter.',
    nightlifeAudit: 'Very limited independent nightlife; mostly hotel bars.',
    walkability: 3,
    registeredPopulation: 47100,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [700, 1300],
    beachDistanceKm: 0.1,
    confidence: 'low',
    verdict: 'reject',
    tags: ['resort-beach', 'weak-nightlife', 'not-walkable-grid'],
    notes: 'Resort enclave popular with Singaporeans; good beach, but lacks walkable urban nightlife.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Desaru',
    ],
  },
  {
    city: 'George Town',
    country: 'Malaysia',
    district: 'Chulia/Love Lane core; Batu Ferringhi beach separate',
    internationalPct: 30,
    domesticPct: 70,
    nightlifeDensity: 760,
    densityVsAmsterdamPct: pct(760),
    densityMethod: 'Great shophouse food/bar grid in George Town, but the swimmable beach zone is far away and much less nightlife-dense.',
    nightlifeCompactness: 4,
    swimmability: 4.5,
    beachQualityScore: 5.0,
    waterCleanlinessScore: 4.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 7.0,
    barClusterRadiusMeters: 1800,
    barsWithin10MinWalk: 8,
    lateNightVenuesCount: 5,
    beachAudit: 'Batu Ferringhi beach (12km away) is usable with water sports but ocean water is murky and jellyfish-prone; town coast is seawall.',
    nightlifeAudit: 'Nightlife and beach are split between George Town heritage core and Batu Ferringhi.',
    walkability: 2,
    registeredPopulation: 794313,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1400],
    beachDistanceKm: 9,
    confidence: 'low',
    verdict: 'reject',
    tags: ['great-city-bars', 'beach-split', 'not-beach-nightlife'],
    notes: 'Penang has superb UNESCO heritage bar life, but swimmable beaches are distant and mediocre.',
    sourceUrls: [
      'https://whc.unesco.org/en/list/1223/',
    ],
  },
  {
    city: 'Malacca',
    country: 'Malaysia',
    district: 'Jonker Street / Bandar Hilir heritage core',
    internationalPct: 20,
    domesticPct: 80,
    nightlifeDensity: 800,
    densityVsAmsterdamPct: pct(800),
    densityMethod: 'Dense heritage food/bar grid, but it is a river/coastal city rather than a swimmable beach vacation spot.',
    nightlifeCompactness: 8,
    swimmability: 1.0,
    beachQualityScore: 3.0,
    waterCleanlinessScore: 2.5,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 10,
    lateNightVenuesCount: 5,
    beachAudit: 'Coastal proxy/Klebang is scenic mudflat/port coast, not a swimmable ocean beach.',
    nightlifeAudit: 'Jonker/Melaka River evening life is good, but it is urban heritage nightlife, not beach nightlife.',
    walkability: 2,
    registeredPopulation: 579000,
    populationYear: 2020,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 8,
    confidence: 'low',
    verdict: 'reject',
    tags: ['city-grid', 'not-swimmable-beach', 'old-objective-false-positive'],
    notes: 'Heritage city with rich food/bar life; coast is non-swimmable strait mudflat.',
    sourceUrls: [
      'https://whc.unesco.org/en/list/1223/',
    ],
  },
  {
    city: 'Kampot',
    country: 'Cambodia',
    district: 'Riverside old town',
    internationalPct: 8,
    domesticPct: 92,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Pleasant riverside bar/cafe town; not a beach destination.',
    nightlifeCompactness: 4,
    swimmability: 1.0,
    beachQualityScore: 3.0,
    waterCleanlinessScore: 4.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 700,
    barsWithin10MinWalk: 10,
    lateNightVenuesCount: 4,
    beachAudit: 'Riverside setting, not ocean; no ocean swim beach in town (Kep is 25km away).',
    nightlifeAudit: 'Riverside bars/live music are pleasant but shallow late-night depth.',
    walkability: 2,
    registeredPopulation: 49700,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 25,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['riverside', 'not-beach', 'quiet'],
    notes: 'Charming river town with French colonial architecture; non-coastal.',
    sourceUrls: [
      'https://tourism.gov.kh/statistics',
    ],
  },
  {
    city: 'Kep',
    country: 'Cambodia',
    district: 'Kep Beach / crab market',
    internationalPct: 4,
    domesticPct: 96,
    nightlifeDensity: 90,
    densityVsAmsterdamPct: pct(90),
    densityMethod: 'Small beach and crab market; very limited nightlife.',
    nightlifeCompactness: 2,
    swimmability: 4.5,
    beachQualityScore: 5.0,
    waterCleanlinessScore: 5.0,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 4.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 6,
    lateNightVenuesCount: 2,
    beachAudit: 'Small artificial white-sand beach strip with shallow calm water; crab market is main attraction.',
    nightlifeAudit: 'Mostly seafood restaurants and guesthouse bars; weak late-night scene.',
    walkability: 4,
    registeredPopulation: 41000,
    populationYear: 2019,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['quiet', 'weak-nightlife', 'small-beach'],
    notes: 'Quiet domestic weekend getaway for Cambodians; quiet evening scene.',
    sourceUrls: [
      'https://tourism.gov.kh/statistics',
    ],
  },
  {
    city: 'Sihanoukville',
    country: 'Cambodia',
    district: 'Serendipity / Otres / casino coast',
    internationalPct: 25,
    domesticPct: 75,
    nightlifeDensity: 240,
    densityVsAmsterdamPct: pct(240),
    densityMethod: 'Some nightlife remains, but city beach reputation, casino/construction pattern, and pollution concerns make it a poor vacation fit.',
    nightlifeCompactness: 5,
    swimmability: 3.0,
    beachQualityScore: 4.5,
    waterCleanlinessScore: 2.5,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 7.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 14,
    lateNightVenuesCount: 8,
    beachAudit: 'Main beaches suffered severe construction runoff and sewage issues during casino boom; Otres is slightly cleaner but affected.',
    nightlifeAudit: 'Fragmented bars/casinos/beach restaurants; still late-night but less coherent than before.',
    walkability: 5,
    registeredPopulation: 89000,
    populationYear: 2019,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['beach-quality-risk', 'casino-skew', 'reject'],
    notes: 'Port and casino city; coastal water cleanliness is a major caveat.',
    sourceUrls: [
      'https://tourism.gov.kh/statistics',
    ],
  },
  {
    city: 'Dumaguete',
    country: 'Philippines',
    district: 'Rizal Boulevard / Dauin access',
    internationalPct: 15,
    domesticPct: 85,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Town nightlife exists, but city has no proper swimmable beach strip; Dauin/Apo are excursions.',
    nightlifeCompactness: 4,
    swimmability: 2.5,
    beachQualityScore: 2.5,
    waterCleanlinessScore: 2.5,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 6.0,
    barClusterRadiusMeters: 1200,
    barsWithin10MinWalk: 8,
    lateNightVenuesCount: 4,
    beachAudit: 'Rizal Boulevard is a concrete seawall promenade; true swimmable dive beaches are 15km south in Dauin.',
    nightlifeAudit: 'Laid-back bar cluster near the boulevard, not a beach-nightlife grid.',
    walkability: 2,
    registeredPopulation: 134103,
    populationYear: 2020,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [550, 1000],
    beachDistanceKm: 12,
    confidence: 'low',
    verdict: 'reject',
    tags: ['expat-town', 'not-beach-strip', 'weak-fit'],
    notes: 'University/expat town with lively seawall promenade; no swim beach in town.',
    sourceUrls: [
      'https://www.citypopulation.de/en/philippines/visayas/admin/negros_oriental/074612__dumaguete/',
    ],
  },
  {
    city: 'Jakarta',
    country: 'Indonesia',
    district: 'SCBD / Senopati / Kemang; Ancol coast proxy',
    internationalPct: 12,
    domesticPct: 88,
    nightlifeDensity: 780,
    densityVsAmsterdamPct: pct(780),
    densityMethod: 'Excellent dense city nightlife, but not connected to a real swimmable vacation beach.',
    nightlifeCompactness: 9,
    swimmability: 1.0,
    beachQualityScore: 2.0,
    waterCleanlinessScore: 1.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 2.0,
    barClusterRadiusMeters: 3000,
    barsWithin10MinWalk: 180,
    lateNightVenuesCount: 80,
    beachAudit: 'Ancol is an artificial polluted bay coast; ocean swimming is strictly unsafe/not recommended.',
    nightlifeAudit: 'SCBD/Senopati/Kemang are excellent domestic mega-city nightlife clusters.',
    walkability: 1,
    registeredPopulation: 10679000,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1400],
    beachDistanceKm: 12,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['baseline', 'city-nightlife', 'not-beach-vacation'],
    notes: 'Non-coastal vacation baseline; polluted bay coast.',
    sourceUrls: [
      'https://jakarta.bps.go.id/',
    ],
  },
  {
    city: 'Surabaya / Soerabaja',
    country: 'Indonesia',
    district: 'Tunjungan / Gubeng / Pakuwon; Kenjeran coast proxy',
    internationalPct: 7,
    domesticPct: 93,
    nightlifeDensity: 520,
    densityVsAmsterdamPct: pct(520),
    densityMethod: 'Local urban nightlife/food districts; coast is separate and not a swimmable vacation beach zone.',
    nightlifeCompactness: 6,
    swimmability: 1.0,
    beachQualityScore: 2.0,
    waterCleanlinessScore: 1.5,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 2.0,
    barClusterRadiusMeters: 3500,
    barsWithin10MinWalk: 60,
    lateNightVenuesCount: 20,
    beachAudit: 'Kenjeran is a muddy Madura strait coast proxy, not a swim beach.',
    nightlifeAudit: 'Urban nightlife exists around central/west Surabaya but is disconnected from the coast.',
    walkability: 1,
    registeredPopulation: 2875000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 950],
    beachDistanceKm: 8,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['baseline', 'local-city', 'not-beach-vacation', 'soerabaja-alias'],
    notes: 'Major industrial port city; non-swimmable muddy strait coast.',
    sourceUrls: [
      'https://surabayakota.bps.go.id/',
    ],
  },
  {
    city: 'Bangkok',
    country: 'Thailand',
    district: 'Sukhumvit / Thonglor / RCA / Khao San',
    internationalPct: 46,
    domesticPct: 54,
    nightlifeDensity: 900,
    densityVsAmsterdamPct: pct(900),
    densityMethod: 'Excellent dense nightlife baseline; no beach.',
    nightlifeCompactness: 10,
    swimmability: 0.0,
    beachQualityScore: 0.0,
    waterCleanlinessScore: 0.0,
    currentSafetyScore: 0.0,
    eveningBeachLifeScore: 0.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 250,
    lateNightVenuesCount: 120,
    beachAudit: 'Non-coastal capital city.',
    nightlifeAudit: 'Huge nightlife density across multiple zones.',
    walkability: 0,
    registeredPopulation: 5527000,
    populationYear: 2020,
    monthlyLocalCostUsd: 1150,
    monthlyCostRangeUsd: [850, 1700],
    beachDistanceKm: 145,
    confidence: 'high',
    verdict: 'reject',
    tags: ['baseline', 'mega-city', 'not-beach'],
    notes: 'Inland mega-city benchmark.',
    sourceUrls: [
      'https://www.mots.go.th/',
    ],
  },
  {
    city: 'Bali',
    country: 'Indonesia',
    district: 'Kuta / Seminyak / Canggu beach-nightlife belt',
    internationalPct: 45,
    domesticPct: 55,
    nightlifeDensity: 850,
    densityVsAmsterdamPct: pct(850),
    densityMethod: 'Dense beach-adjacent nightlife benchmark across Kuta/Seminyak/Canggu.',
    nightlifeCompactness: 8,
    swimmability: 5.0,
    beachQualityScore: 6.5,
    waterCleanlinessScore: 4.5,
    currentSafetyScore: 4.0,
    eveningBeachLifeScore: 9.0,
    barClusterRadiusMeters: 3500,
    barsWithin10MinWalk: 220,
    lateNightVenuesCount: 95,
    beachAudit: 'World famous surf breaks (Canggu/Kuta), but powerful shorebreaks, dangerous rip currents, and seasonal plastic wash up in monsoon make casual ocean swimming poor/hazardous.',
    nightlifeAudit: 'SEA benchmark for dense beach nightlife, but foreign-tourist share is high.',
    walkability: 8,
    registeredPopulation: 4317404,
    populationYear: 2020,
    monthlyLocalCostUsd: 1250,
    monthlyCostRangeUsd: [850, 1900],
    beachDistanceKm: 0.2,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['international-hub', 'beach-adjacent', 'dense-nightlife', 'surf-not-swim'],
    notes: 'Online sentiment: Premier surf break & beach clubs, but ocean swimming is hazardous due to rip currents and seasonal plastic.',
    sourceUrls: [
      'https://bali.bps.go.id/',
    ],
  },
  {
    city: 'Dawei',
    country: 'Myanmar',
    district: 'Dawei town / Maungmagan Beach access',
    internationalPct: 2,
    domesticPct: 98,
    nightlifeDensity: 70,
    densityVsAmsterdamPct: pct(70),
    densityMethod: 'Small local town with restaurants/beer stations; beach is a separate trip.',
    nightlifeCompactness: 2,
    swimmability: 5.5,
    beachQualityScore: 6.5,
    waterCleanlinessScore: 6.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 3.0,
    barClusterRadiusMeters: 1800,
    barsWithin10MinWalk: 5,
    lateNightVenuesCount: 1,
    beachAudit: 'Maungmagan Beach (13km away) is a wide local swim beach.',
    nightlifeAudit: 'Very limited late-night/bar density.',
    walkability: 1,
    registeredPopulation: 146964,
    populationYear: 2014,
    monthlyLocalCostUsd: 550,
    monthlyCostRangeUsd: [400, 800],
    beachDistanceKm: 13,
    confidence: 'low',
    verdict: 'reject',
    tags: ['domestic-heavy', 'quiet', 'myanmar', 'not-beach-grid'],
    notes: 'Low foreign crowd, but weak nightlife density.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Dawei',
    ],
  },
  {
    city: 'Mudon',
    country: 'Myanmar',
    district: 'Mudon town / Setse Beach access',
    internationalPct: 1,
    domesticPct: 99,
    nightlifeDensity: 35,
    densityVsAmsterdamPct: pct(35),
    densityMethod: 'Rural/small-town food and tea/beer venues; not a nightlife district.',
    nightlifeCompactness: 1,
    swimmability: 4.0,
    beachQualityScore: 5.0,
    waterCleanlinessScore: 4.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 2.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 3,
    lateNightVenuesCount: 0,
    beachAudit: 'Setse Beach is 24km away; muddy estuary water.',
    nightlifeAudit: 'Essentially no compact bar/nightlife grid.',
    walkability: 0,
    registeredPopulation: 152300,
    populationYear: 2014,
    monthlyLocalCostUsd: 450,
    monthlyCostRangeUsd: [350, 650],
    beachDistanceKm: 24,
    confidence: 'low',
    verdict: 'reject',
    tags: ['domestic-heavy', 'quiet', 'myanmar', 'no-nightlife-grid'],
    notes: 'Rural town; non-swimmable muddy beach.',
    sourceUrls: [
      'https://en.wikivoyage.org/wiki/Mon_State',
    ],
  },
  {
    city: 'Medan',
    country: 'Indonesia',
    district: 'Kesawan / Polonia / city nightlife; Belawan coast proxy',
    internationalPct: 12,
    domesticPct: 88,
    nightlifeDensity: 470,
    densityVsAmsterdamPct: pct(470),
    densityMethod: 'Domestic-heavy large-city food/cafe/bar density; no usable beach-nightlife transition.',
    nightlifeCompactness: 5,
    swimmability: 0.0,
    beachQualityScore: 1.0,
    waterCleanlinessScore: 1.0,
    currentSafetyScore: 3.0,
    eveningBeachLifeScore: 1.0,
    barClusterRadiusMeters: 3500,
    barsWithin10MinWalk: 55,
    lateNightVenuesCount: 18,
    beachAudit: 'Belawan port is mangrove mudflats, not a beach.',
    nightlifeAudit: 'Real local urban nightlife, but disconnected from any beach.',
    walkability: 0,
    registeredPopulation: 2435252,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [450, 950],
    beachDistanceKm: 24,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['domestic-heavy', 'big-city', 'food', 'not-beach'],
    notes: 'Inland city baseline.',
    sourceUrls: [
      'https://medankota.bps.go.id/',
    ],
  },
  {
    city: 'Semarang / Samarang',
    country: 'Indonesia',
    district: 'Old Town / Simpang Lima nightlife; Marina coast proxy',
    internationalPct: 3,
    domesticPct: 97,
    nightlifeDensity: 430,
    densityVsAmsterdamPct: pct(430),
    densityMethod: 'Domestic city nightlife/cafes around Simpang Lima and Old Town; coast is not a swimmable nightlife strip.',
    nightlifeCompactness: 5,
    swimmability: 1.0,
    beachQualityScore: 2.0,
    waterCleanlinessScore: 2.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 2.0,
    barClusterRadiusMeters: 2800,
    barsWithin10MinWalk: 45,
    lateNightVenuesCount: 14,
    beachAudit: 'Marina beach is an industrial harbor wall, non-swimmable.',
    nightlifeAudit: 'Local urban nightlife exists, but not beach-adjacent.',
    walkability: 1,
    registeredPopulation: 1653524,
    populationYear: 2020,
    monthlyLocalCostUsd: 600,
    monthlyCostRangeUsd: [450, 900],
    beachDistanceKm: 5,
    confidence: 'medium',
    verdict: 'reject',
    tags: ['domestic-heavy', 'big-city', 'samarang-alias', 'not-beach-grid'],
    notes: 'Port city baseline.',
    sourceUrls: [
      'https://semarangkota.bps.go.id/',
    ],
  },
  {
    city: 'Sorong',
    country: 'Indonesia',
    district: 'Sorong city waterfront / Raja Ampat gateway',
    internationalPct: 12,
    domesticPct: 88,
    nightlifeDensity: 160,
    densityVsAmsterdamPct: pct(160),
    densityMethod: 'Gateway town with hotels/seafood/cafes; nightlife is thin.',
    nightlifeCompactness: 3,
    swimmability: 2.0,
    beachQualityScore: 3.0,
    waterCleanlinessScore: 3.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 3.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 10,
    lateNightVenuesCount: 3,
    beachAudit: 'City waterfront is a harbor port; Raja Ampat islands (boat trip away) have pristine water.',
    nightlifeAudit: 'Gateway town, quiet evening life.',
    walkability: 2,
    registeredPopulation: 284410,
    populationYear: 2020,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [600, 1100],
    beachDistanceKm: 3,
    confidence: 'low',
    verdict: 'reject',
    tags: ['raja-ampat-gateway', 'domestic-heavy', 'weak-nightlife'],
    notes: 'Gateway port for Raja Ampat.',
    sourceUrls: [
      'https://sorongkota.bps.go.id/',
    ],
  },
  {
    city: 'Serui',
    country: 'Indonesia',
    district: 'Serui town waterfront / Yapen coast',
    internationalPct: 1,
    domesticPct: 99,
    nightlifeDensity: 45,
    densityVsAmsterdamPct: pct(45),
    densityMethod: 'Small remote town; local food stalls/warungs rather than nightlife.',
    nightlifeCompactness: 1,
    swimmability: 4.0,
    beachQualityScore: 5.0,
    waterCleanlinessScore: 5.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 2.0,
    barClusterRadiusMeters: 1800,
    barsWithin10MinWalk: 3,
    lateNightVenuesCount: 0,
    beachAudit: 'Coastal setting, but not a developed swim beach.',
    nightlifeAudit: 'Too little nightlife.',
    walkability: 1,
    registeredPopulation: 13000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 900],
    beachDistanceKm: 0.5,
    confidence: 'low',
    verdict: 'reject',
    tags: ['very-local', 'remote', 'weak-nightlife'],
    notes: 'Remote Papua island town.',
    sourceUrls: [
      'https://kepulauanyapenkab.bps.go.id/',
    ],
  },
  {
    city: 'Nabire',
    country: 'Indonesia',
    district: 'Nabire waterfront / Pantai Nabire',
    internationalPct: 1,
    domesticPct: 99,
    nightlifeDensity: 70,
    densityVsAmsterdamPct: pct(70),
    densityMethod: 'Local coastal town with restaurants/warungs; limited nightlife.',
    nightlifeCompactness: 2,
    swimmability: 4.0,
    beachQualityScore: 5.0,
    waterCleanlinessScore: 4.0,
    currentSafetyScore: 5.0,
    eveningBeachLifeScore: 3.0,
    barClusterRadiusMeters: 2000,
    barsWithin10MinWalk: 5,
    lateNightVenuesCount: 1,
    beachAudit: 'Basic town coast.',
    nightlifeAudit: 'Quiet local evening scene.',
    walkability: 2,
    registeredPopulation: 172960,
    populationYear: 2020,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [520, 950],
    beachDistanceKm: 0.5,
    confidence: 'low',
    verdict: 'reject',
    tags: ['very-local', 'remote', 'weak-nightlife'],
    notes: 'Remote Papua coast.',
    sourceUrls: [
      'https://nabirekab.bps.go.id/',
    ],
  },
  {
    city: 'Cebu / Mactan',
    country: 'Philippines',
    district: 'Cebu IT Park / Mango / Mactan resort coast',
    internationalPct: 30,
    domesticPct: 70,
    nightlifeDensity: 620,
    densityVsAmsterdamPct: pct(620),
    densityMethod: 'Cebu City has strong nightlife density, while Mactan has resort beaches.',
    nightlifeCompactness: 7,
    swimmability: 5.0,
    beachQualityScore: 5.5,
    waterCleanlinessScore: 4.5,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 4.0,
    barClusterRadiusMeters: 3000,
    barsWithin10MinWalk: 85,
    lateNightVenuesCount: 35,
    beachAudit: 'Mactan resort beaches are usable, but Cebu City coastline is industrial port.',
    nightlifeAudit: 'Excellent domestic city nightlife, separated from beaches.',
    walkability: 2,
    registeredPopulation: 964169,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [600, 1250],
    beachDistanceKm: 10,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['domestic-majority', 'dense-nightlife', 'split-city-beach', 'baseline'],
    notes: 'Big-city baseline.',
    sourceUrls: [
      'https://psa.gov.ph/',
    ],
  },
  {
    city: 'Negros',
    country: 'Philippines',
    district: 'Dumaguete / Bacolod / Sipalay comparison region',
    internationalPct: 8,
    domesticPct: 92,
    nightlifeDensity: 230,
    densityVsAmsterdamPct: pct(230),
    densityMethod: 'Island-level proxy.',
    nightlifeCompactness: 4,
    swimmability: 5.0,
    beachQualityScore: 6.0,
    waterCleanlinessScore: 5.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 4.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 18,
    lateNightVenuesCount: 6,
    beachAudit: 'Good beaches in Sipalay/Dauin, separate from urban bars.',
    nightlifeAudit: 'Mostly local bars.',
    walkability: 3,
    registeredPopulation: 4700000,
    populationYear: 2020,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [500, 1000],
    beachDistanceKm: 8,
    confidence: 'low',
    verdict: 'weak fit',
    tags: ['island-proxy', 'domestic-heavy', 'split-beach-nightlife'],
    notes: 'Regional proxy entry.',
    sourceUrls: [
      'https://psa.gov.ph/',
    ],
  },
  {
    city: 'Panay',
    country: 'Philippines',
    district: 'Iloilo City / Roxas / Antique coast; Boracay excluded',
    internationalPct: 6,
    domesticPct: 94,
    nightlifeDensity: 310,
    densityVsAmsterdamPct: pct(310),
    densityMethod: 'Region-level proxy excluding Boracay.',
    nightlifeCompactness: 5,
    swimmability: 4.0,
    beachQualityScore: 5.0,
    waterCleanlinessScore: 4.0,
    currentSafetyScore: 6.0,
    eveningBeachLifeScore: 4.0,
    barClusterRadiusMeters: 2500,
    barsWithin10MinWalk: 30,
    lateNightVenuesCount: 10,
    beachAudit: 'Mainland Panay beaches are mediocre; Boracay is separate.',
    nightlifeAudit: 'Iloilo is domestic food/bar city.',
    walkability: 2,
    registeredPopulation: 4500000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [500, 950],
    beachDistanceKm: 6,
    confidence: 'low',
    verdict: 'weak fit',
    tags: ['island-proxy', 'domestic-heavy', 'boracay-excluded', 'split-beach-nightlife'],
    notes: 'Excludes Boracay.',
    sourceUrls: [
      'https://psa.gov.ph/',
    ],
  },
  {
    city: 'Palawan',
    country: 'Philippines',
    district: 'Puerto Princesa / El Nido / Coron comparison region',
    internationalPct: 28,
    domesticPct: 72,
    nightlifeDensity: 260,
    densityVsAmsterdamPct: pct(260),
    densityMethod: 'Region-level proxy.',
    nightlifeCompactness: 4,
    swimmability: 8.0,
    beachQualityScore: 9.0,
    waterCleanlinessScore: 8.0,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 5.0,
    barClusterRadiusMeters: 1600,
    barsWithin10MinWalk: 20,
    lateNightVenuesCount: 8,
    beachAudit: 'Pristine islands, but town beaches vary.',
    nightlifeAudit: 'Tourist bars in El Nido/Coron.',
    walkability: 5,
    registeredPopulation: 939594,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.8,
    confidence: 'low',
    verdict: 'weak fit',
    tags: ['region-proxy', 'great-beaches', 'tourist-skew', 'not-dense-nightlife'],
    notes: 'Regional proxy entry.',
    sourceUrls: [
      'https://psa.gov.ph/',
    ],
  },
  {
    city: 'Krabi',
    country: 'Thailand',
    district: 'Ao Nang Beach Road / Night Market / Railay access',
    internationalPct: 28,
    domesticPct: 72,
    nightlifeDensity: 240,
    densityVsAmsterdamPct: pct(240),
    densityMethod: 'Ao Nang beach road forms a compact 1km walkable strip of bars, seafood restaurants, and fire-show beach lounges.',
    nightlifeCompactness: 8,
    swimmability: 8.5,
    beachQualityScore: 8.5,
    waterCleanlinessScore: 8.0,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 38,
    lateNightVenuesCount: 18,
    beachAudit: 'Ao Nang beach has clear swimmable water; adjacent Railay and Phra Nang beaches offer world-class limestone karst swimming.',
    nightlifeAudit: 'Active beach road nightlife with live music, reggae bars, and night market food.',
    walkability: 8.5,
    registeredPopulation: 32000,
    populationYear: 2022,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1400],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['swimmable', 'beach-bars', 'limestone-karst', 'island-hopping'],
    notes: 'Online sentiment: Highly rated for clear emerald karst swimming & compact Ao Nang beach-road nightlife.',
    sourceUrls: [
      'https://www.mots.go.th/',
      'https://en.wikivoyage.org/wiki/Ao_Nang',
    ],
  },
  {
    city: 'Koh Phangan',
    country: 'Thailand',
    district: 'Haad Rin / Baan Tai beach nightlife corridor',
    internationalPct: 42,
    domesticPct: 58,
    nightlifeDensity: 210,
    densityVsAmsterdamPct: pct(210),
    densityMethod: 'Haad Rin village and Baan Tai beach road contain a concentrated grid of beach bars and music venues.',
    nightlifeCompactness: 8,
    swimmability: 8.5,
    beachQualityScore: 9.0,
    waterCleanlinessScore: 8.5,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 9.0,
    barClusterRadiusMeters: 1000,
    barsWithin10MinWalk: 42,
    lateNightVenuesCount: 25,
    beachAudit: 'Pristine white sand beaches (Haad Rin, Secret Beach, Thong Nai Pan) with crystal-clear swimmable water.',
    nightlifeAudit: 'Famous for beach parties, fire shows, and night events; lively evening beach vibe.',
    walkability: 8,
    registeredPopulation: 14000,
    populationYear: 2021,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1350],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'possible',
    tags: ['beach-party', 'swimmable', 'island', 'full-moon'],
    notes: 'Online sentiment: Pristine island swimmability and intense beach nightlife.',
    sourceUrls: [
      'https://www.mots.go.th/',
      'https://en.wikivoyage.org/wiki/Ko_Pha_Ngan',
    ],
  },
  {
    city: 'Koh Chang',
    country: 'Thailand',
    district: 'White Sand Beach / Lonely Beach coastal strip',
    internationalPct: 32,
    domesticPct: 68,
    nightlifeDensity: 160,
    densityVsAmsterdamPct: pct(160),
    densityMethod: 'Linear beach road clusters along White Sand Beach and Lonely Beach with reggae bars and pub venues.',
    nightlifeCompactness: 6,
    swimmability: 8.0,
    beachQualityScore: 8.5,
    waterCleanlinessScore: 8.5,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 7.5,
    barClusterRadiusMeters: 1200,
    barsWithin10MinWalk: 26,
    lateNightVenuesCount: 12,
    beachAudit: 'Long sandy beaches with clear warm water and sunset views.',
    nightlifeAudit: 'Chill beach bar scene; White Sand skews family/resort while Lonely Beach has backpacker/live music nightlife.',
    walkability: 7,
    registeredPopulation: 11000,
    populationYear: 2021,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [600, 1200],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['chill-vibe', 'swimmable', 'island', 'beach-bars'],
    notes: 'Online sentiment: Great swimmable beaches and laid-back beach bars.',
    sourceUrls: [
      'https://www.mots.go.th/',
      'https://en.wikivoyage.org/wiki/Ko_Chang',
    ],
  },
  {
    city: 'Mui Ne',
    country: 'Vietnam',
    district: 'Nguyen Dinh Chieu resort & beach bar strip',
    internationalPct: 22,
    domesticPct: 78,
    nightlifeDensity: 180,
    densityVsAmsterdamPct: pct(180),
    densityMethod: 'Linear coastal road with seafood dining, craft beer pubs, and beach club lounges.',
    nightlifeCompactness: 6,
    swimmability: 7.0,
    beachQualityScore: 7.5,
    waterCleanlinessScore: 7.5,
    currentSafetyScore: 7.5,
    eveningBeachLifeScore: 7.0,
    barClusterRadiusMeters: 1400,
    barsWithin10MinWalk: 28,
    lateNightVenuesCount: 12,
    beachAudit: 'Wide sandy coastline; morning swimming is calm, afternoon brings wind for kite surfing.',
    nightlifeAudit: 'Bustling local seafood night spots and relaxed beach lounges, heavily domestic Saigon weekenders.',
    walkability: 7,
    registeredPopulation: 230000,
    populationYear: 2022,
    monthlyLocalCostUsd: 750,
    monthlyCostRangeUsd: [550, 1100],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'possible',
    tags: ['domestic-heavy', 'beach-bars', 'kitesurfing', 'seafood'],
    notes: 'Online sentiment: Easy Saigon access via highway; good seafood and kitesurf beach vibe.',
    sourceUrls: [
      'https://vietnamtourism.gov.vn/',
      'https://en.wikivoyage.org/wiki/Mui_Ne',
    ],
  },
  {
    city: 'Quy Nhon',
    country: 'Vietnam',
    district: 'Xuan Dieu coastal promenade / An Duong Vuong beach grid',
    internationalPct: 6,
    domesticPct: 94,
    nightlifeDensity: 190,
    densityVsAmsterdamPct: pct(190),
    densityMethod: 'Xuan Dieu beach boulevard features sea-facing cafe/bars, pub streets, and vibrant local night markets.',
    nightlifeCompactness: 8.5,
    swimmability: 8.5,
    beachQualityScore: 8.5,
    waterCleanlinessScore: 8.5,
    currentSafetyScore: 8.5,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 1100,
    barsWithin10MinWalk: 32,
    lateNightVenuesCount: 14,
    beachAudit: 'Clean, broad crescent city beach directly facing clear waters; Ky Co and Bai Xep nearby offer crystal clear blue sea.',
    nightlifeAudit: 'Very domestic Vietnamese nightlife: lively seafood plazas, beachside draft beer, and modern coffee/cocktail bars.',
    walkability: 8.5,
    registeredPopulation: 290000,
    populationYear: 2021,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [450, 950],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['low-foreigners', 'swimmable', 'authentic-local', 'affordable'],
    notes: 'Online sentiment: Widely praised on Reddit as Vietnam’s best authentic swimmable beach city (<6% foreign tourists).',
    sourceUrls: [
      'https://vietnamtourism.gov.vn/',
      'https://en.wikivoyage.org/wiki/Quy_Nhon',
    ],
  },
  {
    city: 'Boracay',
    country: 'Philippines',
    district: "White Beach Station 2 / D'Mall central corridor",
    internationalPct: 38,
    domesticPct: 62,
    nightlifeDensity: 380,
    densityVsAmsterdamPct: pct(380),
    densityMethod: "Dense beachfront walk path with unbroken succession of beach bars, clubs, and live music venues.",
    nightlifeCompactness: 9.5,
    swimmability: 9.5,
    beachQualityScore: 10.0,
    waterCleanlinessScore: 9.0,
    currentSafetyScore: 9.0,
    eveningBeachLifeScore: 9.5,
    barClusterRadiusMeters: 600,
    barsWithin10MinWalk: 55,
    lateNightVenuesCount: 28,
    beachAudit: 'World benchmark powder-white sand beach; shallow, calm, crystal-clear turquoise waters.',
    nightlifeAudit: 'Unbeatable beach-to-bar walkability and nightlife density; highly active late into the night.',
    walkability: 9.5,
    registeredPopulation: 38000,
    populationYear: 2020,
    monthlyLocalCostUsd: 1100,
    monthlyCostRangeUsd: [800, 1600],
    beachDistanceKm: 0.0,
    confidence: 'high',
    verdict: 'possible',
    tags: ['top-beach', 'dense-nightlife', 'walkable-beach', 'white-sand'],
    notes: 'Online sentiment: Global benchmark for white sand swimmability and beachfront nightlife density.',
    sourceUrls: [
      'https://psa.gov.ph/',
      'https://en.wikivoyage.org/wiki/Boracay',
    ],
  },
  {
    city: 'San Juan (La Union)',
    country: 'Philippines',
    district: 'Urbiztondo beach road & surfing nightlife strip',
    internationalPct: 8,
    domesticPct: 92,
    nightlifeDensity: 260,
    densityVsAmsterdamPct: pct(260),
    densityMethod: 'Compact 800m beach road strip packed with craft cocktail spots, live music bars, and beach party venues.',
    nightlifeCompactness: 8.5,
    swimmability: 5.5,
    beachQualityScore: 7.5,
    waterCleanlinessScore: 8.0,
    currentSafetyScore: 7.0,
    eveningBeachLifeScore: 8.5,
    barClusterRadiusMeters: 800,
    barsWithin10MinWalk: 36,
    lateNightVenuesCount: 16,
    beachAudit: 'Grey sand beach with consistent ocean surf breaks; popular for surfing, though dumping waves require care for non-surfer swimming.',
    nightlifeAudit: 'Huge domestic Manila crowd on weekends (Flotsam & Jetsam, Kabsat); vibrant youth & surf nightlife.',
    walkability: 8.5,
    registeredPopulation: 40000,
    populationYear: 2020,
    monthlyLocalCostUsd: 850,
    monthlyCostRangeUsd: [600, 1200],
    beachDistanceKm: 0.1,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['low-foreigners', 'surf-culture', 'domestic-weekend', 'vibrant-bars'],
    notes: 'Online sentiment: Major domestic Manila weekend surf & party hub (92% domestic crowd); grey sand surf break waves.',
    sourceUrls: [
      'https://psa.gov.ph/',
      'https://en.wikivoyage.org/wiki/San_Juan_(La_Union)',
    ],
  },
  {
    city: 'El Nido',
    country: 'Philippines',
    district: 'El Nido Town / Corong Corong beach road',
    internationalPct: 48,
    domesticPct: 52,
    nightlifeDensity: 220,
    densityVsAmsterdamPct: pct(220),
    densityMethod: 'Town grid and Corong Corong beachfront feature sunset cocktail bars, reggae lounges, and live music.',
    nightlifeCompactness: 8,
    swimmability: 8.0,
    beachQualityScore: 8.5,
    waterCleanlinessScore: 8.0,
    currentSafetyScore: 8.0,
    eveningBeachLifeScore: 8.5,
    barClusterRadiusMeters: 700,
    barsWithin10MinWalk: 34,
    lateNightVenuesCount: 15,
    beachAudit: 'Breathtaking Bacuit bay scenery; town beach is ok, nearby Nacpan and Las Cabanas beaches have superb clear swimmable water.',
    nightlifeAudit: 'Lively acoustic and reggae sunset bars; high foreign traveler presence.',
    walkability: 8,
    registeredPopulation: 50000,
    populationYear: 2020,
    monthlyLocalCostUsd: 950,
    monthlyCostRangeUsd: [700, 1400],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['island-hopping', 'limestone', 'beach-bars', 'scenic'],
    notes: 'Online sentiment: Spectacular karst landscape & sunset bars; Nacpan beach is world-class swimmable.',
    sourceUrls: [
      'https://psa.gov.ph/',
      'https://en.wikivoyage.org/wiki/El_Nido',
    ],
  },
  {
    city: 'Gili Trawangan',
    country: 'Indonesia',
    district: 'East Coast beach path & harbor nightlife strip',
    internationalPct: 55,
    domesticPct: 45,
    nightlifeDensity: 420,
    densityVsAmsterdamPct: pct(420),
    densityMethod: 'Entire eastern beach front forms an intense, car-free continuous nightlife strip.',
    nightlifeCompactness: 10,
    swimmability: 9.0,
    beachQualityScore: 8.5,
    waterCleanlinessScore: 9.0,
    currentSafetyScore: 8.5,
    eveningBeachLifeScore: 9.5,
    barClusterRadiusMeters: 500,
    barsWithin10MinWalk: 48,
    lateNightVenuesCount: 22,
    beachAudit: 'Pristine turquoise water with sea turtles right off shore; calm swimmable beach strip.',
    nightlifeAudit: 'Rotating venue night parties, beach bars with live music and DJ sets; zero motorized vehicles.',
    walkability: 10,
    registeredPopulation: 3200,
    populationYear: 2020,
    monthlyLocalCostUsd: 900,
    monthlyCostRangeUsd: [650, 1300],
    beachDistanceKm: 0.0,
    confidence: 'high',
    verdict: 'possible',
    tags: ['car-free', 'turquoise-water', 'nightlife-island', 'walkable'],
    notes: 'Online sentiment: Ultimate car-free party island with crystal clear swimmable waters.',
    sourceUrls: [
      'https://bps.go.id/',
      'https://en.wikivoyage.org/wiki/Gili_Trawangan',
    ],
  },
  {
    city: 'Perhentian Islands',
    country: 'Malaysia',
    district: 'Long Beach beachfront strip (Perhentian Kecil)',
    internationalPct: 35,
    domesticPct: 65,
    nightlifeDensity: 190,
    densityVsAmsterdamPct: pct(190),
    densityMethod: 'Long Beach crescent is lined with rustic wooden beach bars, fire performance shows, and chill lounge spots.',
    nightlifeCompactness: 9.5,
    swimmability: 9.0,
    beachQualityScore: 9.5,
    waterCleanlinessScore: 8.0,
    currentSafetyScore: 9.0,
    eveningBeachLifeScore: 8.0,
    barClusterRadiusMeters: 450,
    barsWithin10MinWalk: 20,
    lateNightVenuesCount: 10,
    beachAudit: 'Pristine white sand and crystal turquoise sea at Long Beach; wastewater management & plastic litter on paths are occasional traveler notes.',
    nightlifeAudit: 'Laid back beach bar nightlife with fire spinners, beach cushions, and acoustic sets right on the sand.',
    walkability: 9.5,
    registeredPopulation: 2000,
    populationYear: 2020,
    monthlyLocalCostUsd: 800,
    monthlyCostRangeUsd: [600, 1200],
    beachDistanceKm: 0.0,
    confidence: 'high',
    verdict: 'top pick',
    tags: ['top-beach', 'crystal-water', 'island-vibe', 'relaxing-nightlife'],
    notes: 'Online sentiment: World-class turquoise swimmability paired with relaxed beachfront bar life; island closes during winter monsoon (Nov-Mar).',
    sourceUrls: [
      'https://www.dosm.gov.my/',
      'https://en.wikivoyage.org/wiki/Perhentian_Islands',
    ],
  },
  {
    city: 'Batam',
    country: 'Indonesia',
    district: 'Nagoya Entertainment District / Waterfront City coast',
    internationalPct: 28,
    domesticPct: 72,
    nightlifeDensity: 310,
    densityVsAmsterdamPct: pct(310),
    densityMethod: 'Nagoya grid contains urban pubs, karaoke, and clubs; coastal resort beaches are 15 mins away.',
    nightlifeCompactness: 7,
    swimmability: 4.0,
    beachQualityScore: 5.5,
    waterCleanlinessScore: 4.0,
    currentSafetyScore: 7.5,
    eveningBeachLifeScore: 6.5,
    barClusterRadiusMeters: 1200,
    barsWithin10MinWalk: 45,
    lateNightVenuesCount: 24,
    beachAudit: 'Nagoya urban core is inland; resort beaches at Nongsa face busy Singapore Strait shipping lanes with mediocre swimmability.',
    nightlifeAudit: 'Bustling weekend nightlife driven by regional weekenders and locals.',
    walkability: 7,
    registeredPopulation: 1200000,
    populationYear: 2020,
    monthlyLocalCostUsd: 700,
    monthlyCostRangeUsd: [500, 1000],
    beachDistanceKm: 5.0,
    confidence: 'medium',
    verdict: 'weak fit',
    tags: ['urban-nightlife', 'weekend-getaway', 'resort-access'],
    notes: 'Online sentiment: Active urban nightlife, but beaches face industrial shipping strait and are separate from bar district.',
    sourceUrls: [
      'https://bps.go.id/',
      'https://en.wikivoyage.org/wiki/Batam',
    ],
  },
  {
    city: 'Pangkor Island',
    country: 'Malaysia',
    district: 'Pasir Bogak & Teluk Nipah beach road',
    internationalPct: 9,
    domesticPct: 91,
    nightlifeDensity: 120,
    densityVsAmsterdamPct: pct(120),
    densityMethod: 'Beach roads at Pasir Bogak and Teluk Nipah feature casual seafood bars, outdoor lounges, and night stalls.',
    nightlifeCompactness: 8,
    swimmability: 8.0,
    beachQualityScore: 8.0,
    waterCleanlinessScore: 8.0,
    currentSafetyScore: 8.5,
    eveningBeachLifeScore: 6.5,
    barClusterRadiusMeters: 900,
    barsWithin10MinWalk: 16,
    lateNightVenuesCount: 6,
    beachAudit: 'Calm, golden sand bays (Teluk Nipah) with smooth clear swimming.',
    nightlifeAudit: 'Chilled domestic Malaysian vibe: seafood BBQs, low-key beachfront drinks, quiet late nights.',
    walkability: 8,
    registeredPopulation: 25000,
    populationYear: 2020,
    monthlyLocalCostUsd: 650,
    monthlyCostRangeUsd: [450, 950],
    beachDistanceKm: 0.1,
    confidence: 'medium',
    verdict: 'possible',
    tags: ['low-foreigners', 'calm-water', 'chill-vibe', 'domestic-heavy'],
    notes: 'Online sentiment: Quiet, highly domestic Malaysian island retreat with peaceful swimmable beaches and low-key evening life.',
    sourceUrls: [
      'https://www.dosm.gov.my/',
      'https://en.wikivoyage.org/wiki/Pangkor',
    ],
  },
];
